
def _commander_reading():
    return [
        rd("Commander Syllabus",                  "commander_syllabus"),
        rd("KTKC Rules and Statutes",             "rules_statutes"),
        rd("KTKC Promotion Manual and By-Laws",   "promo_bylaws"),
    ]

COMMANDER_WEEKS_DEF = []

# ── W1 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 1: The Burden of Senior Command",
    "At the Commander level every decision carries institutional weight. This week examines what it means to hold senior command: the shift from managing people to stewarding the mission, culture, and long-term health of the Order at the highest officer tier.",
    _commander_reading(),
    ["senior command", "institutional stewardship", "mission primacy", "command burden", "officer accountability"],
    [
        q("A Commander notices that a Provincial Master is consistently prioritising membership numbers over member formation quality. The Commander's primary obligation is to:",
          "Praise the growth and defer to the Provincial Master's discretion",
          "Correct the imbalance by reinforcing that mission primacy supersedes metrics",
          "Report the issue to all commanders simultaneously to create peer pressure",
          "Wait until the annual review cycle to raise the concern formally",
          "B",
          "Senior command demands mission stewardship above all metrics. A Commander must intervene when institutional priorities drift from formation quality toward vanity numbers."),
        q("A newly appointed Commander feels reluctant to overrule a popular officer's decision that is technically wrong. This reluctance most directly undermines which principle?",
          "Collegial harmony within the officer corps",
          "The Commander's obligation to command accountability over personal comfort",
          "The Provincial Master's authority to manage his own officers",
          "The value of democratic deliberation in Templar governance",
          "B",
          "Command accountability requires Commanders to act on correct principle regardless of popularity. Reluctance to correct a wrong decision for social comfort is a dereliction of senior command duty."),
        q("Which statement best captures the shift that occurs when an officer reaches Commander-level responsibility?",
          "The Commander focuses on executing chapter-level programmes personally",
          "Responsibility shifts from direct leadership of individuals to stewardship of the institution's culture and mission",
          "The Commander's role is primarily ceremonial and advisory",
          "Command at this level is indistinguishable from the Captain's role but with a wider territory",
          "B",
          "Commander-level responsibility is institutional, not individual. The focus moves from leading specific people to stewarding culture, doctrine, and the long-term health of the Order."),
        q("A Commander is told that intervening in a subordinate chapter's internal conflict would be 'overstepping.' The correct response is to:",
          "Agree and monitor from a distance to respect chapter autonomy",
          "Evaluate whether the conflict threatens mission or standards, and act if it does",
          "Delegate the decision to the Marshal to avoid controversy",
          "Immediately dissolve the chapter's leadership team",
          "B",
          "Senior command is not overstepping when mission or standards are at risk. The Commander must evaluate substance, not defer to appeals to autonomy when the institution's health is in question."),
        q("The 'burden of senior command' primarily refers to:",
          "The administrative paperwork and reporting requirements at the Commander level",
          "The weight of decisions whose consequences shape the institution for years beyond the commander's tenure",
          "The physical demands of travelling to multiple chapter locations",
          "The difficulty of maintaining personal friendships while holding authority",
          "B",
          "The burden of senior command is the long-term institutional consequence of every decision — choices made at this level shape culture, standards, and mission alignment well beyond the Commander's own tenure."),
        q("A Commander learns that a chapter has been operating with an unwritten 'gentlemen's agreement' that bypasses a formal statute. The Commander should:",
          "Formalise the agreement since it has worked in practice",
          "Correct the deviation and reinstate the statute, regardless of how long the practice has existed",
          "Notify the Provincial Master but take no direct action",
          "Defer to the chapter's officers who are closer to the situation",
          "B",
          "Senior command carries institutional stewardship. Informal workarounds that bypass formal statutes erode governance integrity; the Commander's duty is to reinstate correct practice, not legitimise deviation through tolerance."),
        q("Which of the following best illustrates 'mission primacy' at the Commander level?",
          "Prioritising the Commander's personal vision for the Order over established doctrine",
          "Ensuring every resource, appointment, and programme decision serves the Order's core formation mission",
          "Completing all administrative tasks before addressing formation concerns",
          "Advancing the interests of the largest and most influential chapters in the province",
          "B",
          "Mission primacy means that all Commander-level decisions — resources, appointments, programmes — are evaluated against the Order's core formation mission, not personal vision or chapter influence."),
        q("A Commander is approached by a Major who wants to bypass standard promotion protocols for a highly popular candidate. The Commander should:",
          "Approve the exception given the candidate's popularity and the Major's support",
          "Decline and reinforce that promotion protocols exist to maintain institutional integrity across all candidates",
          "Escalate to the Grand Master to avoid responsibility",
          "Approve provisionally and review after six months",
          "B",
          "Promotion protocols maintain institutional integrity. A Commander who allows exceptions for popularity undermines the standards that give all ranks meaning and sets a precedent that erodes command authority."),
        q("What distinguishes the Commander's accountability from that of lower-ranking officers?",
          "Commanders are accountable only to the Grand Master, not to the officers beneath them",
          "Commanders bear accountability both upward to the Grand Master and downward to the entire officer corps and membership they oversee",
          "Commanders are primarily accountable to their chapter members through democratic processes",
          "Accountability at the Commander level is moral rather than structural",
          "B",
          "Senior command carries bidirectional accountability: upward to Grand Master authority and downward to every officer and member in the Commander's scope. This dual accountability is the defining feature of senior command."),
        q("A Commander observes that his own leadership style has become conflict-avoidant over time. This recognition should prompt him to:",
          "Accept it as a natural evolution toward more collaborative leadership",
          "Deliberately recalibrate toward direct, principled engagement even when uncomfortable, as command demands it",
          "Delegate all conflict situations to the Marshal and Seneschal",
          "Seek a formal leave of absence to reflect before taking further action",
          "B",
          "Self-awareness is a senior command virtue, but it must lead to correction. A conflict-avoidant Commander fails in his stewardship duty; the recognition of the pattern obligates active recalibration."),
    ]
))

# ── W2 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 2: Senior Command in the Knights Templar",
    "This week situates the Commander role within the specific structure of the KTKC. We examine how senior command is defined, delegated, and exercised within the Order's constitutional framework, and how the Commander differs from the Major and the Grand Master.",
    _commander_reading(),
    ["constitutional framework", "delegated authority", "command structure", "Grand Master", "Commander role"],
    [
        q("Under the KTKC constitutional framework, the Commander's authority is best described as:",
          "Absolute within the province, limited only by his own conscience",
          "Delegated from the Grand Master, bounded by statute, and accountable upward and downward",
          "Equivalent to the Grand Master's authority for all operational purposes",
          "Advisory only, with real authority reserved to the elected chapter officers",
          "B",
          "All KTKC authority is delegated and bounded. The Commander holds real executive authority but it derives from the Grand Master, operates within statutory limits, and carries accountability in both directions."),
        q("The clearest functional distinction between the Major and the Commander is:",
          "The Major focuses on regional growth; the Commander focuses on ceremonial duties",
          "The Major develops officers within a region; the Commander oversees multiple regions and carries institutional-level accountability",
          "The Major holds more administrative power; the Commander is a figurehead",
          "There is no meaningful distinction — both roles are interchangeable at senior levels",
          "B",
          "The Major's scope is regional officer development. The Commander's scope is multi-regional institutional oversight, carrying accountability for culture and doctrine across a larger domain."),
        q("A Commander who acts outside his statutory authority to achieve a good outcome has:",
          "Demonstrated admirable initiative that the Order should recognise",
          "Violated the constitutional framework even if the outcome is positive",
          "Fulfilled his mission-primacy obligation by prioritising results",
          "Set a useful precedent for future Commanders facing similar situations",
          "B",
          "Good outcomes do not justify exceeding statutory authority. A Commander who acts outside his mandate undermines the constitutional framework that makes all authority legitimate and trustworthy."),
        q("In the KTKC command structure, which principle governs the relationship between the Commander and the Grand Master?",
          "The Commander may override Grand Master guidance when it conflicts with local conditions",
          "The Commander serves as the Grand Master's executive extension, carrying out senior policy within his scope",
          "The Grand Master serves in an advisory role to the Commander in provincial matters",
          "The two offices are co-equal, with the Grand Master serving as a tie-breaker",
          "B",
          "The Commander is the Grand Master's executive extension at the senior officer level — carrying out policy and doctrine within the Commander's scope, not substituting his own judgment for the Grand Master's mandate."),
        q("A Commander who regularly consults the KTKC Rules and Statutes before making significant decisions is demonstrating:",
          "Lack of confidence in his own judgment",
          "Proper constitutional governance — senior authority is exercised within, not above, the governing documents",
          "Excessive caution that slows institutional response time",
          "Deference that signals he is not ready for Commander-level responsibility",
          "B",
          "Consulting governing documents is a mark of constitutional literacy, not weakness. Senior command is exercised within the framework of statute, and a Commander who ignores documents in favour of intuition risks illegal or invalid decisions."),
        q("What is the significance of the Commander's role in defining 'what good looks like' across his scope?",
          "It gives the Commander personal authority to revise the Order's standards at will",
          "The Commander's consistent modelling and articulation of standards sets the benchmark against which all subordinate officers calibrate",
          "It means the Commander's personal preferences become the Order's official norms",
          "Standard-setting is the Grand Master's exclusive function; the Commander only enforces",
          "B",
          "At senior command levels, the Commander's lived standards become the visible benchmark. When the Commander consistently models and articulates what good looks like, subordinate officers calibrate upward; when he does not, standards drift downward."),
        q("A chapter reports that their Major has been absent and uncommunicative for weeks. The Commander's correct first action is to:",
          "Wait for the Major to re-engage on his own initiative",
          "Contact the Major directly to assess the situation and re-establish command continuity",
          "Immediately replace the Major through an emergency appointment",
          "Inform the chapter to manage without a Major until the next election cycle",
          "B",
          "Command continuity is a Commander-level responsibility. When a Major is absent, the Commander must proactively re-establish contact and assess the situation before escalating to replacement or other measures."),
        q("The principle of 'constitutional command' means that a Commander's first loyalty is to:",
          "The senior officers who nominated him for the role",
          "The Order's governing documents and the mission they enshrine",
          "The chapters with the most members and resources",
          "His personal philosophy of leadership, which should inform his interpretation of the statutes",
          "B",
          "Constitutional command means the governing documents — statutes, bylaws, the Promotion Manual — take precedence over personal loyalty, nominations, or personal philosophy. The Commander serves the mission as defined in the Order's constitution."),
        q("A Commander is offered an unofficial side agreement by a Major that would benefit three chapters but bypass normal reporting. The Commander should:",
          "Accept if the outcome is clearly beneficial to those chapters",
          "Decline and redirect through formal channels, explaining that informal arrangements erode institutional trust",
          "Accept provisionally and document it privately for his own records",
          "Consult only with the affected chapters before deciding",
          "B",
          "Informal side agreements bypass the governance structures that make authority transparent and legitimate. A Commander who accepts them — even for good outcomes — normalises opaque decision-making and erodes institutional trust."),
        q("The KTKC structure places the Commander above Majors primarily because:",
          "The Commander has more years of service than any Major",
          "The Commander carries accountability for institutional coherence across the scope that Majors individually cannot provide",
          "Seniority in the Order is determined by length of membership, and Commanders are always older",
          "The Commander role is primarily a reward for distinguished service",
          "B",
          "The Commander's position reflects structural accountability, not seniority or reward. The role exists because someone must hold institutional coherence across multiple regions — a scope no individual Major can cover."),
    ]
))

# ── W3 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 3: The Offices of Marshal and Seneschal",
    "The Marshal and Seneschal are the Commander's two principal staff officers. This week examines their distinct functions, how the Commander uses each office effectively, and the risks of conflating or neglecting either role.",
    _commander_reading(),
    ["Marshal", "Seneschal", "staff functions", "command delegation", "office distinction"],
    [
        q("A Commander who assigns both operational coordination and administrative compliance to the Marshal has:",
          "Simplified the command structure for greater efficiency",
          "Conflated the Marshal and Seneschal functions, likely creating overload and gaps in one area",
          "Made a reasonable adjustment given the Seneschal's inexperience",
          "Demonstrated best practice for lean command teams",
          "B",
          "The Marshal and Seneschal are distinct offices for a reason. Conflating them risks both operational overload and administrative neglect — the Commander's job is to deploy each office within its proper function."),
        q("The Seneschal's primary function in the Commander's staff is best described as:",
          "Leading training exercises and officer development programmes",
          "Overseeing administrative compliance, records, and the internal governance of the command",
          "Managing external relationships with other Orders and civil authorities",
          "Serving as the Commander's personal spokesman in public settings",
          "B",
          "The Seneschal is the administrative conscience of the command — responsible for records, compliance, and governance integrity. This is distinct from the Marshal's operational coordination role."),
        q("A Commander notices that the Marshal is making decisions that fall within the Seneschal's remit without consulting him. The correct response is to:",
          "Allow it since the Marshal is more senior and experienced",
          "Clearly re-establish each officer's scope and enforce the distinction going forward",
          "Reassign one of the offices to a single individual to prevent overlap",
          "Refer the matter to the Grand Master since it is an internal officer dispute",
          "B",
          "Office integrity requires that the Commander actively maintain role distinctions. Allowing the Marshal to encroach on Seneschal responsibilities creates confusion, resentment, and governance gaps."),
        q("In a time-sensitive operational crisis, the Commander delegates execution authority to the Marshal. This is appropriate when:",
          "The Commander is unavailable and wants to avoid any decision being made",
          "The matter falls squarely within the Marshal's operational function and the Commander has set clear parameters",
          "The Seneschal disagrees with the operational approach and needs to be bypassed",
          "The Commander wants to test the Marshal's decision-making under pressure",
          "B",
          "Delegating to the Marshal is appropriate and correct when the matter is operational and parameters are clear. Proper delegation is not abandonment — the Commander retains accountability and must set scope."),
        q("A Seneschal flags a compliance gap that the Marshal believes is unimportant operationally. The Commander should:",
          "Side with the Marshal since operational continuity is the priority",
          "Treat the Seneschal's concern as substantive — governance gaps matter regardless of operational inconvenience",
          "Ask them to resolve it between themselves",
          "Table the matter until the next formal review",
          "B",
          "Governance compliance is not optional when inconvenient. The Commander must take the Seneschal's compliance concerns seriously, because administrative gaps often become institutional vulnerabilities — especially during audits or leadership transitions."),
        q("Which scenario best illustrates the Marshal's function?",
          "Reviewing chapter membership records for accuracy before an annual report",
          "Coordinating the logistics of a multi-chapter training exercise, including scheduling and officer deployment",
          "Drafting the Commander's official correspondence to the Grand Master",
          "Maintaining the minutes of the Commander's staff meetings",
          "B",
          "The Marshal's function is operational coordination — scheduling, logistics, officer deployment across exercises and programmes. Record-keeping, correspondence, and minutes fall under Seneschal or administrative functions."),
        q("A Commander who rarely meets separately with the Seneschal and Marshal risks:",
          "Building strong team cohesion by treating both offices as equal",
          "Missing distinct intelligence from each office and inadvertently letting one dominate the other",
          "Creating an impression of favouritism toward neither officer",
          "Demonstrating appropriate hands-off leadership at the senior command level",
          "B",
          "Regular separate engagement with each staff officer ensures the Commander receives unfiltered input from both functions. Without this, one office tends to dominate briefings and the other's concerns go unheard."),
        q("The Marshal reports that a chapter's drill quality has degraded significantly. The Seneschal simultaneously reports that the same chapter is behind on required paperwork. The Commander should interpret this as:",
          "Two unrelated administrative issues to be handled separately through each office",
          "A systemic signal about the chapter's overall health that warrants direct Commander engagement",
          "A sign that both the Marshal and Seneschal are being overly critical",
          "An operational matter for the Marshal to resolve without further Commander involvement",
          "B",
          "Convergent signals from both the operational (Marshal) and administrative (Seneschal) domains indicate systemic chapter health problems. The Commander should treat this as requiring direct engagement rather than routing through separate offices independently."),
        q("Why does the KTKC maintain distinct Marshal and Seneschal offices rather than a single 'Chief of Staff'?",
          "Tradition requires two offices as a matter of historical form",
          "Operational and administrative functions require different mindsets, and separation prevents either from subordinating the other",
          "It doubles the number of senior staff positions to reward more officers",
          "A single officer could not be trusted with both sets of responsibilities",
          "B",
          "The structural separation of Marshal and Seneschal ensures that operational urgency does not consistently override administrative rigour, or vice versa. Both functions have equal standing and distinctive competencies."),
        q("A Commander preparing for a major transition (new officers being appointed) should prioritise which action involving the Seneschal?",
          "Having the Seneschal lead the farewell ceremonies for outgoing officers",
          "Ensuring the Seneschal conducts a full administrative handover audit before new officers take their positions",
          "Asking the Seneschal to informally brief the new officers on office culture",
          "Delegating transition planning entirely to the Marshal since it is an operational event",
          "B",
          "Transitions are prime moments for governance gaps. The Seneschal's role is to ensure records, compliance documentation, and administrative continuity are in order before new officers assume office — this protects the institution from inherited disorder."),
    ]
))

# ── W4 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 4: Doctrine, Mission, and Institutional Identity",
    "The Commander is the senior guardian of KTKC doctrine. This week examines how doctrine is maintained, transmitted, and defended at the senior command level, and how the Commander's role as doctrinal steward shapes institutional identity across all subordinate bodies.",
    _commander_reading(),
    ["doctrine", "institutional identity", "doctrinal stewardship", "mission transmission", "cultural continuity"],
    [
        q("A chapter begins promoting a new 'core value' that is not found in KTKC doctrine. As Commander, you should:",
          "Encourage innovation since it shows the chapter is engaged",
          "Evaluate whether the value contradicts or dilutes established doctrine, and correct if it does",
          "Formally adopt the value Order-wide if it is popular",
          "Ignore it since chapters have autonomy over their internal culture",
          "B",
          "The Commander is the doctrinal steward. Unofficial 'core values' that contradict or compete with established doctrine fragment institutional identity. The Commander must evaluate and correct such drift."),
        q("Doctrinal stewardship at the Commander level is best understood as:",
          "Memorising and reciting the Order's statutes at official ceremonies",
          "Actively ensuring that every programme, appointment, and communication reflects the Order's established doctrine and mission",
          "Delegating all doctrinal questions to the Marshal and Seneschal",
          "Writing new doctrine to replace outdated sections of the Statutes",
          "B",
          "Doctrinal stewardship is active and pervasive — every decision, communication, and appointment carries doctrinal implications. The Commander guards doctrine by ensuring it is lived, not just cited."),
        q("A Major proposes a new training curriculum that significantly de-emphasises the spiritual formation pillar of KTKC training. The Commander should:",
          "Approve it if the operational content is sound",
          "Reject it as inconsistent with KTKC's mission, which integrates spiritual formation as a core pillar",
          "Approve it for a trial period to gather member feedback",
          "Defer to the Major's expertise in training design",
          "B",
          "KTKC doctrine integrates spiritual formation as a core training pillar. A curriculum that de-emphasises it is not merely a training preference issue — it represents a doctrinal deviation that the Commander must correct."),
        q("Institutional identity in the KTKC is primarily transmitted through:",
          "Promotional materials and social media presence",
          "The consistent alignment of programmes, officer conduct, and formation practices with established doctrine",
          "The Commander's personal charisma and public communications",
          "Annual ceremonies and awards banquets",
          "B",
          "Institutional identity is transmitted through lived alignment — when programmes, officer conduct, and formation practices consistently reflect doctrine, members internalise identity through experience, not just ceremonial exposure."),
        q("A Commander notices that different regions under his scope have significantly divergent interpretations of the same statute. This divergence most directly threatens:",
          "The Commander's personal reputation for consistency",
          "Doctrinal integrity and the institutional identity that depends on shared understanding",
          "Only the regions with the minority interpretation",
          "Nothing significant, since local adaptation is healthy",
          "B",
          "Divergent statutory interpretations fragment the institutional identity that depends on shared doctrine. The Commander's role is to bring interpretations into alignment, not tolerate local variation on matters of doctrine."),
        q("Why is it problematic for a Commander to introduce novel personal doctrine — even compelling ideas — as if they were established KTKC doctrine?",
          "It is not problematic; Commanders are expected to develop doctrine",
          "It confuses members about what is officially mandated versus personally advocated, eroding doctrinal clarity",
          "It is only problematic if the Grand Master explicitly disapproves",
          "It is fine as long as the Commander is transparent about the source",
          "B",
          "Personal ideas presented as institutional doctrine deceive members about what is required versus suggested, and over time erode the clarity that makes doctrine a reliable anchor for institutional identity."),
        q("Cultural continuity across leadership transitions is primarily the Commander's responsibility because:",
          "The Commander controls the ceremony at which new officers are installed",
          "The Commander is the most senior officer consistently present across transitions and must actively transmit institutional values to incoming leaders",
          "Cultural transmission happens automatically through the Order's ceremonies",
          "The Seneschal handles cultural continuity through administrative records",
          "B",
          "Leadership transitions are the highest-risk moment for cultural drift. The Commander's presence and active transmission of institutional values ensures incoming officers inherit the culture intact rather than improvising their own."),
        q("A long-standing Commander retires and his successor immediately begins making sweeping changes. The most dangerous risk of rapid wholesale change is:",
          "Political opposition from officers loyal to the previous Commander",
          "The unintentional dismantling of doctrinal and cultural elements that gave the institution its coherence",
          "Reduced efficiency during the transition period",
          "The new Commander being perceived as disloyal",
          "B",
          "Rapid wholesale change risks destroying the doctrinal and cultural foundations of the institution alongside whatever genuinely needed updating. The correct approach is discerning, sequential reform — not wholesale replacement."),
        q("Which action by a Commander best demonstrates active doctrinal stewardship?",
          "Commissioning an annual survey of member satisfaction",
          "Regularly evaluating whether programmes, appointments, and Officer training are aligned with KTKC's doctrinal pillars",
          "Personally attending every chapter event in his scope",
          "Increasing the frequency of formal ceremonial events",
          "B",
          "Active doctrinal stewardship requires the Commander to systematically evaluate alignment — not just attendance. Checking that programmes, appointments, and training reflect the doctrinal pillars is the concrete practice of stewardship."),
        q("A Commander who models doctrinal fidelity in his personal conduct primarily accomplishes:",
          "Compliance through fear of being corrected by the Commander",
          "Embodied transmission — subordinate officers learn doctrine through observed behaviour more than through instruction",
          "A public reputation that benefits his career",
          "Formal compliance that satisfies audit requirements",
          "B",
          "Embodied transmission is the most powerful doctrinal teaching tool at the senior command level. Officers who observe the Commander consistently living the doctrine internalise it more deeply than through any formal instruction."),
    ]
))

# ── W5 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 5: Authority, Judgment, and Command Presence",
    "Effective senior command requires more than positional authority — it requires cultivated judgment and visible command presence. This week examines how Commanders develop and exercise judgment under ambiguity, and what constitutes authentic command presence in the KTKC context.",
    _commander_reading(),
    ["command presence", "judgment under ambiguity", "positional authority", "cultivated authority", "command credibility"],
    [
        q("A Commander is asked to rule on an unusual situation not explicitly covered by existing statute. The best approach is to:",
          "Delay ruling until the Grand Master amends the statute",
          "Apply the spirit of existing doctrine and the mission to the situation, documenting the rationale for the record",
          "Rule in favour of whoever brought the matter since they clearly need support",
          "Declare the matter outside his jurisdiction and refuse to rule",
          "B",
          "Senior command judgment requires applying the spirit of doctrine to novel situations. Refusing to rule or demanding prior statutory coverage abdicates leadership. Documenting the rationale ensures accountability and provides precedent."),
        q("Command presence in the KTKC context is best defined as:",
          "Physical stature and a commanding voice that commands attention in ceremonial settings",
          "The consistent alignment of authority, conduct, and decision-making that gives others confidence the Commander can be trusted",
          "The Commander's skill at public speaking and formal address",
          "The rank insignia and ceremonial dress that visually signals the Commander's position",
          "B",
          "Command presence is relational and behavioral, not physical. It arises when the Commander's authority, personal conduct, and decisions consistently align — this alignment is what gives others confidence that the Commander can be trusted with senior responsibility."),
        q("A Commander faces a situation where the technically correct decision will cause short-term pain for a respected chapter. Judgment requires him to:",
          "Soften the decision to reduce the pain and maintain relationships",
          "Make the correct decision, explain the rationale clearly, and manage the relationship through the process",
          "Defer the decision indefinitely to avoid the conflict",
          "Let the Major handle it to insulate the Commander from the consequences",
          "B",
          "Senior command judgment means making the correct decision even when it is painful, while managing the relational consequences with honesty and care. Softening or deferring a correct decision to avoid short-term pain is a failure of judgment."),
        q("A Commander who consistently defers difficult decisions upward to the Grand Master is demonstrating:",
          "Appropriate humility and respect for the chain of command",
          "A failure of senior command judgment — decisions within his mandate must be made at his level",
          "Best practice for preventing unilateral mistakes at the senior level",
          "Effective use of the escalation process",
          "B",
          "Consistently escalating decisions that belong at the Commander level is an abdication of senior command responsibility. The Grand Master appointed the Commander to exercise judgment within his mandate, not to route every difficult call upward."),
        q("What is the primary risk of a Commander who relies exclusively on positional authority rather than cultivated authority?",
          "He will be respected too much to receive honest feedback",
          "Compliance will be surface-level and will evaporate when he is absent or challenged",
          "Officers will defer excessively and never develop their own initiative",
          "He will become too focused on ceremony rather than operations",
          "B",
          "Positional authority produces compliance without commitment — people follow the rank, not the person. When the Commander is absent, challenged, or pressured, surface compliance collapses. Cultivated authority earns genuine commitment."),
        q("A Commander who publicly admits a past decision was wrong and explains what he learned is demonstrating:",
          "Weakness that will undermine confidence in his authority",
          "Command credibility — authentic authority includes the capacity to correct course and model intellectual honesty",
          "Political skill in managing his public image",
          "A need for mentorship from the Grand Master",
          "B",
          "Admitting error and naming the learning is a mark of senior command credibility. Officers who model intellectual honesty build deeper trust than those who project infallibility. This is a component of cultivated authority."),
        q("During a crisis, a Commander remains calm and methodical while subordinate officers are agitated. This behaviour primarily functions to:",
          "Signal to subordinates that the Commander is emotionally detached",
          "Regulate the command environment — the Commander's composure sets the emotional ceiling for the entire group",
          "Buy time for the Commander to secretly consult the Grand Master",
          "Demonstrate that the crisis is not serious",
          "B",
          "Senior command presence includes emotional regulation under pressure. The Commander's composure sets the de facto emotional ceiling for the command — when he is calm, the group can function; when he panics, the group fragments."),
        q("A Commander makes a judgment call that turns out to be wrong. The most important thing he must do next is:",
          "Find the subordinate officer whose advice he followed and hold them accountable",
          "Own the decision, assess what led to the error, correct the course, and absorb the accountability",
          "Attribute the error to incomplete information provided by the Marshal",
          "Wait to see if the consequences are noticed before taking any action",
          "B",
          "Command accountability means owning decisions — including wrong ones. Deflecting blame onto subordinates or circumstances while one holds authority is a fundamental failure of command character."),
        q("Which scenario best illustrates genuine command judgment rather than rule-following?",
          "A Commander enforces a regulation even when it clearly does not fit the unusual situation at hand",
          "A Commander applies the principles behind a regulation to a novel situation the regulation did not anticipate",
          "A Commander refuses to act until he receives written instructions covering the exact scenario",
          "A Commander defers to the chapter's own judgment to avoid overstepping",
          "B",
          "Rule-following applies established rules mechanically. Genuine command judgment applies the principles behind rules to situations the rules did not anticipate — this is what distinguishes a commander from an administrator."),
        q("Command presence is undermined most directly when a Commander:",
          "Makes unpopular decisions that some officers disagree with",
          "Behaves differently in private than in public, creating inconsistency between visible authority and private character",
          "Insists on formal address and proper ceremonies at official events",
          "Holds high standards for officer conduct",
          "B",
          "Command presence depends on consistency between public authority and private character. When the two diverge — when the Commander behaves very differently when not observed — the cultivated authority he appears to hold dissolves."),
    ]
))

# ── W6 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 6: Senior Officer Alignment and Direction",
    "The Commander must align a diverse group of senior officers — Majors, Marshals, Seneschals, Captains — toward a unified institutional direction. This week examines how to set direction, maintain alignment, and correct drift without micromanagement.",
    _commander_reading(),
    ["officer alignment", "direction-setting", "anti-micromanagement", "senior officer development", "unified direction"],
    [
        q("A Commander who provides detailed instructions for every decision made by Majors under his command is most likely to produce:",
          "Consistent high-quality outcomes across all regions",
          "Officers who execute well but cannot exercise independent command judgment when the Commander is absent",
          "Officers who deeply appreciate the clarity and support",
          "A reputation as a hands-on Commander who cares about quality",
          "B",
          "Micromanagement produces dependent officers. When the Commander is absent or the situation is novel, officers trained to wait for instructions fail. Senior officer development requires delegating decision space alongside accountability."),
        q("The most effective way for a Commander to maintain alignment without micromanaging is to:",
          "Schedule daily check-in calls with every Major",
          "Set clear doctrinal and mission-anchored direction, then hold officers accountable for outcomes rather than methods",
          "Assign the Marshal to shadow each Major's decisions",
          "Create a detailed operations manual that covers every possible scenario",
          "B",
          "Direction-setting and outcome accountability allow officers to exercise judgment within clear mission parameters. This approach develops officer capacity while maintaining coherence — the antithesis of micromanagement."),
        q("A Major persistently implements programmes in a way that achieves acceptable outcomes but consistently bypasses the Commander's stated direction. The Commander should:",
          "Accept the deviation since outcomes are acceptable",
          "Address the pattern directly — consistent direction-bypassing signals an alignment problem that will worsen over time",
          "Reassign the Major immediately without further discussion",
          "Have the Seneschal document the pattern for future reference without addressing it",
          "B",
          "Acceptable outcomes do not validate persistent direction-bypassing. If the pattern is not addressed, the Major effectively signals that the Commander's direction is optional — a precedent that erodes authority across all senior officer relationships."),
        q("During an officer development meeting, a Major challenges the Commander's stated strategic direction in front of peers. The Commander should:",
          "Immediately discipline the Major for insubordination",
          "Engage the challenge substantively in the moment, and use the opportunity to reinforce the rationale for the direction",
          "Ignore the challenge to de-escalate in a public setting",
          "Agree to review the direction privately to end the confrontation",
          "B",
          "A substantive public challenge to direction should be engaged with direct reasoning, not suppressed. This demonstrates command confidence, models intellectual honesty, and reinforces direction through explanation rather than mere authority."),
        q("Senior officer alignment is most threatened by:",
          "Officers who ask too many questions about the rationale for decisions",
          "Ambiguity in the Commander's stated direction that allows officers to fill gaps with conflicting assumptions",
          "A highly collaborative decision-making culture",
          "Officers who implement direction faster than the Commander expected",
          "B",
          "Ambiguity in direction is the primary driver of misalignment. When the Commander is unclear, officers fill the gap with their own assumptions — and those assumptions diverge. Precise direction is the foundation of coherent senior officer action."),
        q("A Commander discovers that two Majors have developed competing approaches to a shared challenge, neither of which is wrong but both of which create confusion for chapters that report to both. The Commander should:",
          "Let the Majors compete and adopt whichever approach proves more effective",
          "Establish a unified approach, explaining the rationale, and require both Majors to align",
          "Ask the Seneschal to document both approaches and let chapters choose",
          "Avoid intervening since both approaches are technically acceptable",
          "B",
          "Competing valid approaches at the Major level create institutional incoherence downstream. The Commander's role is to establish unified direction even when multiple options are individually defensible."),
        q("Which practice most effectively develops senior officer alignment over time?",
          "Annual speeches by the Commander at large ceremonial gatherings",
          "Regular structured dialogue in which the Commander explains the 'why' behind direction and invites genuine input before finalising",
          "Detailed written directives distributed via email",
          "Delegation of all direction-setting to the Marshal",
          "B",
          "Alignment is deepened when officers understand the reasoning behind direction and have genuine input into its development. Officers who own the 'why' align their decisions to it naturally; those who only receive directives comply without internalising."),
        q("A Commander is informed that several senior officers feel the current strategic direction is misaligned with chapter realities on the ground. The correct first step is to:",
          "Dismiss the concern since strategic direction is the Commander's prerogative",
          "Create a structured opportunity to hear the concerns, evaluate their substance, and adjust direction if warranted",
          "Instruct the Marshal to identify the officers raising concerns and assess whether they are disloyal",
          "Issue a written reaffirmation of the current direction to signal it is not open to revision",
          "B",
          "Senior officer concerns about strategic alignment represent valuable ground-truth intelligence. The Commander who dismisses them without evaluation risks maintaining direction that has lost connection to operational reality."),
        q("A Commander's direction is most credible when it is:",
          "Delivered forcefully and without qualification",
          "Grounded in the Order's doctrine, clearly explained, and consistently embodied in the Commander's own conduct",
          "Changed frequently to demonstrate responsiveness to officer feedback",
          "Restricted to high-level principles that leave maximum room for officer discretion",
          "B",
          "Directional credibility is built through doctrinal grounding, transparent explanation, and personal embodiment. Direction that is loudly delivered but inconsistently lived erodes faster than direction quietly held and consistently modelled."),
        q("After a period of significant change, a Commander wants to reset senior officer alignment. The most effective approach is to:",
          "Hold a single large meeting to announce the new direction and consider the matter settled",
          "Conduct a deliberate re-alignment process: shared reflection on what changed, why, and what the stabilising direction going forward is — engaging each Major individually and collectively",
          "Issue written guidance and allow officers to ask questions via email",
          "Wait for the change to settle naturally before attempting any explicit re-alignment",
          "B",
          "Re-alignment after change requires deliberate process — shared reflection, individual engagement, collective clarification. A single announcement treats alignment as compliance; the deliberate process builds genuine shared understanding."),
    ]
))

# ── W7 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 7: Crisis Leadership and Difficult Decisions",
    "Commanders will face crises — internal conflicts, member scandals, institutional failures, external threats. This week examines what principled crisis leadership looks like at the senior command level: decision-making under pressure, communication protocols, and the post-crisis responsibility to learn.",
    _commander_reading(),
    ["crisis leadership", "principled decision-making", "command under pressure", "communication protocols", "post-crisis learning"],
    [
        q("During a crisis in a chapter under his command, a Commander's first obligation is to:",
          "Protect the Order's public reputation by controlling information",
          "Stabilise the situation through clear authority, assess the facts accurately, and act on principle rather than politics",
          "Delegate entirely to the Marshal since crises are operational",
          "Consult all affected officers before taking any action to ensure consensus",
          "B",
          "In a crisis, principled authority stabilises. The Commander's first obligation is to assess accurately and act on principle — not to protect reputation or seek consensus before the situation is under control."),
        q("A Commander learns of a serious member misconduct allegation against a well-respected Major. The politically easy path is to conduct a quiet investigation and quietly resolve it. The principled path is to:",
          "Follow the quiet path since public process would harm the Major's reputation unfairly",
          "Apply the same investigation and accountability process that would apply to any officer, without exception",
          "Refer the matter to the chapter members to vote on appropriate consequences",
          "Delay until the allegation source can be verified to be credible",
          "B",
          "Principled crisis leadership requires equal process regardless of the officer's standing. Quiet resolution for the well-respected while full process applies to the ordinary is the definition of institutional partiality, which destroys trust."),
        q("When a Commander is forced to make a consequential decision without complete information, the right approach is to:",
          "Refuse to decide until all information is available, regardless of time pressure",
          "Decide based on the best available information and clearly established principle, document the reasoning, and remain open to revision as new information emerges",
          "Let the Marshal decide to preserve the Commander's options",
          "Make the most conservative possible decision to minimise downside risk",
          "B",
          "Waiting for complete information in a time-pressured crisis is not a neutral option — the delay itself is a decision with consequences. Acting on best available information with documented principle, open to revision, is the correct command approach."),
        q("During a public crisis, a Commander gives a clear, brief public statement that acknowledges the situation without prejudging the investigation. This approach is preferable because:",
          "It satisfies the media's demand for a response and ends further inquiry",
          "It demonstrates institutional accountability and prevents speculation from filling the information vacuum",
          "It protects the Commander legally by creating a record of his awareness",
          "It signals to members that the situation is resolved",
          "B",
          "In a crisis, information vacuums fill with speculation that can be more damaging than the facts. A brief, principled, non-prejudicial statement demonstrates accountability and controls the narrative responsibly without prejudging outcomes."),
        q("A Commander who consistently avoids making difficult decisions until they become crises is demonstrating:",
          "Appropriate patience and due diligence",
          "A failure of proactive command judgment — unaddressed problems compound into crises",
          "Respect for subordinate officers' autonomy",
          "An evidence-based approach to decision-making",
          "B",
          "Problems avoided at the manageable stage become crises at the critical stage. The Commander's proactive judgment is what prevents manageable issues from compounding — avoidance is not caution, it is negligence."),
        q("After a crisis is resolved, a Commander who immediately moves to the next issue without structured post-crisis reflection is most likely to:",
          "Be seen as decisive and forward-looking by his officers",
          "Miss the learning opportunity that the crisis provided, and repeat the conditions that enabled it",
          "Demonstrate appropriate command priority management",
          "Protect team morale by not dwelling on past failures",
          "B",
          "Post-crisis reflection is where institutional learning happens. A Commander who skips it misses the chance to identify systemic conditions that enabled the crisis — and those conditions will produce the next crisis."),
        q("A crisis reveals that a chapter's internal conflict has been building for months while the Major reported 'all well.' The Commander's accountability question is:",
          "Only about the Major's dishonesty in reporting",
          "Both about the Major's reporting and the Commander's own oversight system that failed to detect the building conflict",
          "Exclusively about the chapter members who allowed the conflict to escalate",
          "None — the Commander cannot be held responsible for what he was not told",
          "B",
          "Senior command accountability includes the accountability for oversight systems. If monthly reports said 'all well' while a serious conflict built, the Commander must examine both the Major's reporting and his own detection systems."),
        q("The most dangerous error a Commander can make during a crisis is:",
          "Acting too quickly before all facts are confirmed",
          "Letting the desire to protect the institution's image override the obligation to act on truth and principle",
          "Communicating too transparently with the membership about the situation",
          "Involving too many officers in the response process",
          "B",
          "When image protection overrides truth and principle in a crisis, the institutional response compounds the original harm. Officers and members observe the cover-up logic and lose trust in the institution's integrity more deeply than in the original crisis."),
        q("A Commander who has never discussed crisis protocols with his staff officers before a crisis occurs has:",
          "Correctly prioritised normal operations over unlikely scenarios",
          "Left the command exposed — crisis response requires pre-established protocols, roles, and communication agreements",
          "Demonstrated appropriate confidence in his officers' judgment",
          "Made a reasonable resource allocation decision",
          "B",
          "Crisis preparation is a senior command responsibility, not a response to crisis. Commanders who establish protocols, roles, and communication agreements before crises occur enable far more effective response when crises happen."),
        q("During a crisis, several officers give the Commander conflicting accounts of what happened. The Commander should:",
          "Accept the account from the most senior officer present",
          "Reserve judgment until independent verification is possible, making clear that decisions will be based on verified facts",
          "Accept the majority account since more officers corroborate it",
          "Accept the account most consistent with his prior understanding of the situation",
          "B",
          "Conflicting accounts are common in the early stages of a crisis. Reserving judgment until independent verification is possible prevents the Commander from anchoring prematurely on a false narrative that shapes subsequent decisions poorly."),
    ]
))

# ── W8 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 8: Succession, Appointments, and Officer Formation",
    "The Commander shapes the institutional future through appointments and officer formation. This week examines how senior command decisions about officer selection, succession, and ongoing formation determine the Order's health for years beyond any individual Commander's tenure.",
    _commander_reading(),
    ["succession planning", "officer appointments", "officer formation", "institutional future", "appointment integrity"],
    [
        q("A Commander who makes appointments based primarily on personal loyalty to the appointee is most likely to:",
          "Create a cohesive team that performs well under pressure",
          "Weaken institutional capacity by prioritising relationship over qualification and character",
          "Demonstrate appropriate trust in his closest advisors",
          "Follow KTKC best practice for building command coherence",
          "B",
          "Appointment by personal loyalty rather than qualification and character fills the officer corps with officers whose primary allegiance is personal rather than institutional — a systemic vulnerability that emerges most clearly during crises."),
        q("Succession planning at the Commander level means:",
          "Identifying a single preferred successor and grooming only that officer",
          "Deliberately developing a pool of officers capable of senior command so that institutional capacity does not depend on any single individual",
          "Ensuring the current Commander stays in position long enough to see all programmes through completion",
          "Delegating succession decisions entirely to the Grand Master",
          "B",
          "Institutional succession planning creates depth — a pool of capable officers rather than dependence on one designated heir. Single-heir thinking creates vulnerability if that officer is unavailable when needed."),
        q("A highly capable officer applies for appointment but has a documented pattern of poor conduct toward subordinates. The Commander should:",
          "Appoint and monitor — capability should not be wasted",
          "Decline or defer the appointment until the conduct pattern is credibly resolved",
          "Appoint to a role where the officer has no subordinates",
          "Consult only the officer's peers since they are best positioned to evaluate",
          "B",
          "Capability without character is a liability at the officer level. Appointing a capable officer with a documented conduct pattern signals that conduct standards are negotiable, which corrupts the entire appointment system."),
        q("Officer formation after appointment is the Commander's responsibility because:",
          "New officers cannot be expected to self-develop at senior levels",
          "Appointment without ongoing formation produces officers who plateau rather than grow into the full demands of their role",
          "The Grand Master requires Commanders to file officer development reports",
          "Formation prevents new officers from making mistakes during their first year",
          "B",
          "Appointment is the beginning of an officer's formation at that level, not the completion of it. A Commander who appoints and then withholds ongoing formation produces officers who plateau and eventually fall short of the role's full demands."),
        q("A Commander learns that a Major is being considered for advancement but has not been told. The Commander's ethical obligation is to:",
          "Keep the discussion confidential until the decision is finalised",
          "Ensure the Major is properly informed and given the opportunity to demonstrate readiness if the process requires it",
          "Accelerate the decision to prevent the Major from hearing through informal channels",
          "Delegate the notification to the Seneschal",
          "B",
          "Officers have a right to engage honestly in their own advancement process. Conducting evaluations for advancement in complete secrecy from the candidate fails the standard of honest officer formation and can damage trust if discovered."),
        q("Which factor should receive the greatest weight when the Commander evaluates an officer for a major appointment?",
          "The officer's popularity among chapter members",
          "Demonstrated alignment of character, competence, and commitment to KTKC mission across diverse situations",
          "The officer's personal relationship with the Commander",
          "The officer's length of service in the Order",
          "B",
          "The appointment decision should weigh character, competence, and mission commitment as demonstrated across contexts — not popularity, relationship, or seniority. These three factors predict sustained performance better than any proxy measure."),
        q("A Commander who has served for a long tenure and has never engaged in succession planning leaves the institution:",
          "In strong shape because of the continuity he provided",
          "Dependent on an individual and vulnerable to institutional disruption when he transitions",
          "With officers who are well-trained and ready for any transition",
          "Following best practice by allowing the Grand Master to manage succession",
          "B",
          "Long tenure without succession planning creates institutional dependence on a single person. When that person transitions, the institution often experiences a power vacuum or leadership crisis that adequate succession planning would have prevented."),
        q("An outgoing Commander should prioritise which action regarding his successor?",
          "Briefing the successor extensively on his own strategic agenda so it continues",
          "Providing a comprehensive transition that includes institutional history, unresolved issues, key relationships, and honest assessment of officer and chapter health",
          "Stepping back immediately to give the successor room to lead without influence",
          "Staying in an advisory role for at least two years to ensure continuity",
          "B",
          "A comprehensive transition brief enables the incoming Commander to inherit institutional intelligence, not just a title. Prioritising personal agenda continuity fails the institution; stepping back immediately without briefing abandons it."),
        q("A Commander who regularly conducts candid one-on-one development conversations with Majors is building:",
          "Personal loyalty from officers who appreciate the attention",
          "A formation relationship that develops officer judgment and prepares them for greater responsibility",
          "A surveillance mechanism to detect officer concerns before they become problems",
          "A record that supports future appointment decisions",
          "B",
          "Candid development conversations are the primary vehicle of officer formation at the senior level. The Commander who invests consistently builds an officer corps with deeper judgment and greater readiness for advancement."),
        q("The integrity of the appointments process across the entire Commander's scope depends most on:",
          "The Commander personally interviewing every candidate for every position",
          "Consistent application of the same character, competence, and mission-commitment standards regardless of the candidate's personal relationship to the Commander",
          "A formal voting process in which all senior officers participate",
          "Detailed documentation filed with the Grand Master's office",
          "B",
          "Appointment integrity is about consistency — the same standards applied regardless of personal relationship. When the Commander applies different standards to allies and strangers, the entire process is corrupted and officers notice immediately."),
    ]
))

# ── W9 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 9: Discipline, Correction, and Justice at the Highest Officer Level",
    "Senior command carries the most consequential discipline and correction responsibilities. This week examines how Commanders administer justice with both firmness and mercy, the specific obligations when discipline must reach the officer level, and how correction at this level is inseparable from formation.",
    _commander_reading(),
    ["senior discipline", "command justice", "officer correction", "firmness and mercy", "disciplinary process"],
    [
        q("A Commander must apply discipline to a Major for a serious breach of conduct. The correct sequence is:",
          "Immediate public announcement → private investigation → formal sanction",
          "Private investigation → clear finding → proportionate sanction → formal documentation",
          "Informal warning → second warning → third warning → sanction",
          "Referral to the Seneschal for administrative handling without Commander involvement",
          "B",
          "Disciplinary process integrity requires: establishing facts first (private investigation), reaching a clear finding, applying proportionate sanction, and documenting formally. Skipping investigation or reversing the order compromises justice."),
        q("A Commander who refuses to discipline a senior officer for a serious breach because 'it would set a bad precedent to discipline at this level' has:",
          "Correctly prioritised institutional stability",
          "Inverted the accountability logic — senior officers are more accountable, not less, and allowing serious breaches to go uncorrected sets a far worse precedent",
          "Applied appropriate discretion given the officer's seniority",
          "Demonstrated understanding of the long-term institutional costs of conflict",
          "B",
          "Seniority increases accountability, not immunity. Refusing to discipline senior officers for serious breaches sends the message that rank protects from accountability — which corrupts the entire disciplinary culture."),
        q("Firmness and mercy in senior discipline are best understood as:",
          "Competing values where one must be chosen depending on the severity of the offence",
          "Complementary principles: firmness ensures standards are upheld, mercy ensures the person is treated with dignity and the correction aims at restoration where possible",
          "Mercy is applied first; firmness is reserved for repeat offences",
          "Firmness is the Commander's obligation; mercy is the Grand Master's prerogative",
          "B",
          "Firmness and mercy are not opposites. Firmness upholds the standard; mercy treats the person as capable of restoration and worthy of dignity. Both must be present in principled discipline."),
        q("A Commander receives pressure from multiple senior officers to drop a disciplinary process against a popular Major. The Commander should:",
          "Consider the pressure as a legitimate input into the disciplinary decision",
          "Proceed with the process on the merits, making clear that disciplinary integrity cannot be subject to popularity-based pressure",
          "Delay the process to allow social pressure to dissipate",
          "Transfer the process to the Grand Master to insulate himself",
          "B",
          "Disciplinary processes that can be stopped by social pressure are not processes — they are performances. The Commander's obligation is to proceed on the merits; yielding to pressure destroys the credibility of all future disciplinary actions."),
        q("When correction is given to an officer at the Major level, the goal beyond applying consequences should always include:",
          "Ensuring the officer understands the Commander has the authority to sanction",
          "The officer's genuine understanding of what failed and a clear path to restoration where possible",
          "Deterring other officers through the visible consequences applied",
          "A formal public statement acknowledging the correction",
          "B",
          "Discipline at the senior level that only applies consequences misses its formation purpose. The Commander's goal is genuine understanding and, where possible, restoration — this is what transforms discipline from punishment into formation."),
        q("An officer self-reports a serious mistake to the Commander before it is discovered. This self-reporting:",
          "Is irrelevant to the disciplinary outcome since the action was still wrong",
          "Is a significant factor in the Commander's assessment — the willingness to self-report reflects character and should be weighed in determining the proportionate response",
          "Should be treated identically to an externally-discovered breach to maintain consistency",
          "Fully excuses the breach and no formal process is needed",
          "B",
          "Self-reporting reflects character — the officer prioritised honesty and institutional integrity over self-protection. This character evidence is legitimately relevant to proportionate response, though it does not nullify the need for appropriate accountability."),
        q("A Commander who documents every disciplinary action in the formal record is:",
          "Being overly bureaucratic and creating an adversarial climate",
          "Protecting institutional integrity — formal records ensure consistency, prevent revisionism, and provide evidence if patterns emerge",
          "Undermining the privacy of officers who deserve to move past corrective episodes",
          "Creating legal liability for the Order",
          "B",
          "Formal documentation serves institutional integrity: it enforces consistency, prevents decisions from being revised to protect relationships, and makes patterns visible over time. The alternative — undocumented discipline — is invisible and unreliable."),
        q("A Commander must discipline a close personal friend at the Major level. The correct approach is to:",
          "Recuse himself and refer to the Marshal to avoid the appearance of bias in either direction",
          "Proceed with the full standard process, applying the same standards he would apply to any officer, regardless of personal relationship",
          "Apply a lighter process given the established trust between them",
          "Consult the Seneschal about whether the relationship creates a formal conflict of interest",
          "B",
          "Personal relationships cannot alter the disciplinary standard. Recusing creates the impression that senior officers can avoid accountability by cultivating personal relationships with the Commander. Proceeding with the standard demonstrates that process is process."),
        q("After administering discipline, a Commander's ongoing obligation to the sanctioned officer is:",
          "To monitor closely for any further breach and apply immediate escalated sanctions",
          "To treat the officer as capable of restoration, provide formation support, and evaluate conduct fairly going forward without permanent stigma",
          "To maintain professional distance to prevent any appearance of favouritism",
          "To report the sanctions to all senior officers for transparency",
          "B",
          "Post-discipline formation is part of the Commander's obligation. Treating a corrected officer as permanently compromised denies the possibility of restoration that KTKC formation explicitly affirms."),
        q("A Commander who never administers any formal discipline in a long tenure has most likely:",
          "Built a culture of excellence that naturally prevents breaches",
          "Either avoided situations that required discipline or failed to address breaches when they occurred",
          "Demonstrated the highest level of pastoral command leadership",
          "Created a formation culture so strong that formal discipline became unnecessary",
          "B",
          "Long tenures without any formal discipline almost always reflect avoidance rather than perfection. The Commander who never disciplines likely allowed breaches to pass without formal response — normalising deviation and eroding standards."),
    ]
))

# ── W10 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 10: Stewardship of Culture, Communication, and Morale",
    "The Commander is the primary architect of institutional culture at the senior level. This week examines how Commanders build, sustain, and repair the culture, communication, and morale of the institution through intentional practices and the power of embodied example.",
    _commander_reading(),
    ["institutional culture", "morale stewardship", "communication architecture", "culture repair", "embodied example"],
    [
        q("The most powerful mechanism by which a Commander shapes institutional culture is:",
          "Formal written culture statements and values documents",
          "Consistent personal conduct that embodies the culture he expects of others",
          "Mandatory culture training for all officers and members",
          "Annual Commander's addresses at formal events",
          "B",
          "Culture is transmitted most powerfully through observed behaviour. When the Commander consistently embodies the values he espouses, they become real and credible. When he does not, no training or document substitutes."),
        q("Institutional morale under the Commander's scope is most at risk when:",
          "Officers disagree openly with strategic direction",
          "The Commander's communications create ambiguity about direction, priorities, or the institution's future — leaving officers and members filling gaps with anxiety",
          "Members raise concerns through formal channels",
          "The Commander makes unpopular but necessary decisions",
          "B",
          "Morale is heavily influenced by communicative clarity. When the Commander leaves direction or future ambiguous, anxiety fills the gap. Even difficult truths clearly communicated preserve morale better than comfortable ambiguity."),
        q("A Commander observes that sarcasm and cynicism have become the dominant tone among his senior officers in informal settings. He should interpret this as:",
          "Normal venting behaviour that does not affect formal performance",
          "A cultural warning sign — informal tone among senior officers reflects and amplifies culture throughout the institution",
          "Evidence that officers feel comfortable being candid with one another",
          "A sign that the current strategic direction is unpopular",
          "B",
          "Senior officer informal tone is not private — it cascades downward. When cynicism and sarcasm become the dominant informal register of senior officers, those tones migrate into chapter culture. The Commander must address the root conditions driving them."),
        q("A Commander wants to improve communication quality across his scope. The highest-leverage single action is:",
          "Implementing a new reporting software system for all chapters",
          "Modelling the communication standard he expects — clarity, honesty, brevity, and responsiveness — in every interaction",
          "Hosting a communication skills workshop for all senior officers",
          "Increasing the frequency of mandatory written reports",
          "B",
          "Communication culture is set by the senior officer's modelled behaviour more than by any system or training. Officers calibrate their own communication to the standard they observe in the Commander."),
        q("A culture of fearful compliance — where officers report 'all well' regardless of reality — is most directly caused by:",
          "Members who are not fully committed to the mission",
          "A command environment in which officers have learned that honest negative reports produce punishment rather than support",
          "Poor communication skills among middle-level officers",
          "Excessive bureaucratic reporting requirements",
          "B",
          "Fearful compliance cultures are created by command environments that punish honest reporting. Officers who report 'all well' while problems build have learned — usually through direct experience — that accurate negative reports harm them."),
        q("Following a period of significant institutional difficulty, a Commander wants to restore morale. The most effective first step is:",
          "Announcing new programmes and initiatives to signal forward momentum",
          "Acknowledging the difficulty honestly, naming what was learned, and articulating a credible path forward anchored in the mission",
          "Replacing the senior officers most associated with the difficult period",
          "Hosting a social event to shift the emotional tone",
          "B",
          "Morale restoration after difficulty requires honest acknowledgment — not denial or distraction. Officers and members rebuild trust when they see the Commander name reality accurately, draw learning, and offer a credible forward direction."),
        q("A Commander who communicates important information only through formal channels, never informally engaging with officers, is most likely to experience:",
          "Highly efficient communication with minimal misinterpretation",
          "Informal information vacuums that fill with rumour and speculation",
          "Greater respect from officers who appreciate formal structure",
          "Lower administrative burden since fewer communications are required",
          "B",
          "Formal channels transmit decisions; informal engagement transmits context, intent, and relationship. A Commander who communicates only formally leaves the informal information environment unattended — and it fills with rumour."),
        q("An officer raises a serious culture concern with the Commander confidentially. The Commander's first obligation is to:",
          "Assure the officer that the concern will be shared with all senior officers immediately",
          "Evaluate the concern on its merits, protect the officer's confidentiality to the extent possible, and take appropriate action",
          "Determine whether the officer raising the concern has personal motivations",
          "Refer the concern to the Seneschal for formal documentation",
          "B",
          "Confidential culture concerns require careful handling: substantive evaluation, appropriate action, and protection of the reporting officer's position. Officers who see confidentiality violated stop raising concerns — which silences the Commander's most important intelligence source."),
        q("The Commander's communication during a transition period (new appointments, strategic shift) should prioritise:",
          "Minimising information sharing until all decisions are finalised",
          "Transparent, timely communication about what is known, what is still being decided, and when updates will come",
          "Reassurance that nothing significant is changing to maintain stability",
          "Formal announcements delivered simultaneously to all levels without prior individual engagement",
          "B",
          "Transitions generate anxiety. Transparent, timely communication — even when decisions are not yet finalised — maintains trust and prevents rumour from filling the void. Silence during transitions is experienced as concealment, not caution."),
        q("A Commander who explicitly celebrates formation milestones, service to the mission, and character growth among his officers is using recognition to:",
          "Create dependency on external validation among officers",
          "Reinforce the cultural values he wants to propagate, making visible what the institution holds as genuinely important",
          "Fulfil a ceremonial obligation of the Commander's role",
          "Build personal loyalty that will support him during future difficult decisions",
          "B",
          "Recognition is a culture-shaping tool. What the Commander celebrates publicly defines what the institution values. Celebrating formation, service, and character communicates that these — not metrics or rank — are the true markers of success."),
    ]
))

# ── W11 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 11: Senior Command Practicum",
    "This week integrates the prior ten weeks through applied practicum exercises. Commanders-in-training engage with complex, multi-dimensional scenarios drawn from real command situations — developing the capacity to hold competing obligations simultaneously and make principled decisions under pressure.",
    _commander_reading(),
    ["command integration", "applied judgment", "competing obligations", "principled decision-making", "senior command practicum"],
    [
        q("A Major contacts you to report that a chapter in his region is threatening to operate independently of the Order's governance if their preferred candidate is not appointed to a senior role. Your first action as Commander is to:",
          "Immediately appoint the preferred candidate to prevent the schism",
          "Engage the chapter's leadership directly to reaffirm constitutional governance while refusing to negotiate under threat",
          "Ignore the threat and let the Major handle it at his level",
          "Refer to the Grand Master without any direct engagement",
          "B",
          "Constitutional governance is non-negotiable. Rewarding threats with concessions normalises the tactic and invites future extortion. The Commander engages directly, reaffirms authority, and makes clear that appointments are made on merit — not under threat."),
        q("You are preparing for a major ceremonial event when a crisis erupts in a chapter three regions away. Both require your personal presence. You should:",
          "Attend the ceremony since the event was scheduled first",
          "Assess which situation requires Commander-level presence most critically; delegate the other with clear authority and parameters",
          "Cancel both events to demonstrate impartiality",
          "Ask the Grand Master to make the decision for you",
          "B",
          "Senior command requires real-time priority judgment. The Commander assesses which situation requires his direct authority most critically, then delegates the other with genuine authority — not nominal oversight. Refusing to choose is itself a poor choice."),
        q("A senior officer you have trusted for years brings you credible evidence that another senior officer you equally trust has been dishonest in his reports. How do you proceed?",
          "Accept the evidence at face value and act immediately",
          "Initiate a structured, confidential fact-finding process before reaching any conclusion, treating both officers fairly throughout",
          "Confront the accused officer immediately in the presence of the accuser",
          "Place both officers on leave pending the outcome",
          "B",
          "Credible evidence requires structured verification, not immediate action. Interpersonal trust is not a substitute for due process. The Commander's integrity depends on treating allegations from trusted sources with the same procedural fairness as allegations from any source."),
        q("During a practicum review, a candidate Commander consistently makes technically correct decisions but explains them poorly to his officers. The most important development feedback is:",
          "His technical accuracy is sufficient; communication is a secondary skill",
          "At the Commander level, the ability to communicate the reasoning behind decisions is itself a command responsibility — unexplained correct decisions erode trust nearly as much as wrong ones",
          "He should delegate communications to the Seneschal",
          "Communication style is personal preference and should not be assessed",
          "B",
          "At the Commander level, unexplained correct decisions feel arbitrary to those who must implement them. The capacity to explain reasoning is not a soft skill — it is a core command function that builds the understanding necessary for genuine alignment."),
        q("You have been Commander for three years when you learn that several long-standing practices in your scope have drifted significantly from KTKC doctrine — and that this drift began before your tenure. Your responsibility is:",
          "To document the drift and formally attribute it to your predecessor",
          "To correct the drift regardless of its origin — you are accountable for current practice",
          "To wait for the next formal audit before acting on inherited problems",
          "To seek guidance from all affected chapters before making any corrections",
          "B",
          "The Commander who inherits drift is accountable for correcting it. The origin of drift is relevant to understanding how it occurred, but it does not release the current Commander from the obligation to restore correct practice."),
        q("Three Majors come to you simultaneously with separate urgent requests, each of which is legitimate. You have capacity to address only one personally. The principle guiding your prioritisation should be:",
          "Serve the most senior Major first as a matter of protocol",
          "Triage by which situation, if unaddressed, poses the greatest risk to mission integrity or institutional health",
          "Serve whoever arrived first to demonstrate procedural fairness",
          "Address all three partially to signal equal concern",
          "B",
          "Mission-risk triage is the correct prioritisation logic. Protocol and procedural fairness matter in routine operations; in capacity-constrained urgent situations, the Commander must apply judgment about which non-response would cause the most institutional harm."),
        q("A candidate Commander in practicum says: 'In a real crisis I would trust my instincts, not a process.' How should this be evaluated?",
          "Positively — instinct reflects deep internalised experience",
          "Negatively — at the Commander level, 'instinct' must be grounded in deeply internalised principle; pure instinct without process produces arbitrary outcomes in novel situations",
          "Neutrally — both instinct and process have valid roles",
          "Positively only if the candidate can cite past evidence of sound instinct",
          "B",
          "Genuine command instinct is cultivated principle — not the absence of process. Commanders who trust raw instinct without process become unpredictable in novel situations. The practicum goal is to develop instinct that is indistinguishable from internalised principle."),
        q("You learn that a chapter's Captain has been running excellent formation programmes but systematically under-reporting financial activities. Your response integrates:",
          "Praise for the formation and silence on the financial issue to preserve his motivation",
          "Full accountability for the financial irregularity alongside acknowledgment of the formation strength — excellence in one area does not offset misconduct in another",
          "Immediate removal pending investigation",
          "A private warning with no formal process since the formation programmes are too valuable to risk",
          "B",
          "Programme excellence does not create immunity from accountability. Allowing misconduct in one area while praising another creates a transactional accountability culture — officers learn they can 'buy' tolerance with good performance in visible areas."),
        q("A practicum scenario asks you to design a Commander-level oversight system for your scope. The system's primary architecture should be built around:",
          "Maximum information collection — the more data, the better the oversight",
          "Selective, high-signal indicators that reveal mission alignment and officer health without creating surveillance culture",
          "Annual formal inspections of every chapter in the scope",
          "Monthly written reports from every officer in the command chain",
          "B",
          "Effective oversight is about signal quality, not data volume. Systems built on maximum information collection create surveillance cultures that incentivise positive reporting. High-signal selective indicators give the Commander genuine intelligence without choking the officer corps in administration."),
        q("At the conclusion of the practicum, the most important question a Commander-candidate should be able to answer honestly is:",
          "How many decisions have I made correctly in the exercises?",
          "What are the conditions under which my judgment is most likely to fail, and how do I safeguard against those conditions?",
          "Which of my officers would I trust most in a crisis?",
          "Have I fulfilled all the formal requirements of the Commander role?",
          "B",
          "The highest-value practicum outcome is honest self-knowledge about the conditions of one's own failure. A Commander who can name the circumstances that degrade his judgment — fatigue, personal loyalty, time pressure — can build structures and relationships that compensate for those vulnerabilities."),
    ]
))

# ── W12 ──────────────────────────────────────────────────────────────────────
COMMANDER_WEEKS_DEF.append((
    "Week 12: Capstone Preparation and Commander's Board Review",
    "The final week synthesises the full Commander curriculum into board review preparation. Candidates demonstrate integrated senior command competence across all five pillars: Knowledge, Judgment, Service, Character, and Communication.",
    _commander_reading(),
    ["board review", "integrated competence", "five pillars", "capstone synthesis", "senior command readiness"],
    [
        q("A board reviewer asks: 'Describe a moment when institutional duty required you to act against your personal preference.' The best response demonstrates:",
          "That the candidate has never had to choose between duty and preference",
          "Specific self-aware reflection on the tension, the reasoning used to resolve it, and the outcome — showing command character over personal comfort",
          "That personal preference and duty always align in a well-formed officer",
          "That the candidate defers all difficult decisions upward",
          "B",
          "The board is assessing command character — the capacity to act on institutional duty when it conflicts with personal preference. A specific, self-aware answer with honest reflection on tension demonstrates more than a clean answer that avoids the difficulty."),
        q("During the Commander's Board, a reviewer presents a scenario in which correct action will damage a senior officer's career. The candidate's correct response is to:",
          "Propose the action that minimises career damage to preserve morale",
          "Identify the correct action, state it clearly, and acknowledge the career cost as a real consequence that the Commander must manage with care but cannot allow to override principle",
          "Defer the decision to the Grand Master to avoid responsibility",
          "Ask for a private follow-up to discuss the political dimensions",
          "B",
          "The board assesses whether the candidate holds principle above political calculation. Naming the correct action while honestly acknowledging its cost is a stronger board response than either softening the action or pretending the cost does not exist."),
        q("The Knowledge pillar at the Commander level board is primarily assessed by:",
          "Memorised recitation of statute provisions",
          "The candidate's ability to apply doctrinal principles to novel scenarios — demonstrating that knowledge is operative, not merely stored",
          "The number of source documents the candidate can cite by name",
          "Written examination scores from earlier in the programme",
          "B",
          "At the Commander level, the Knowledge pillar is tested through application — not recitation. The board wants to see whether the candidate's knowledge shapes judgment under novel conditions, not whether he can quote the documents."),
        q("The Judgment pillar at the Commander level is distinguished from earlier program levels because:",
          "The candidate is expected to know more statutes",
          "Judgment at this level involves holding multiple competing institutional obligations simultaneously and making decisions whose consequences ripple across many bodies and officers",
          "The candidate is only responsible for decisions within his immediate chapter",
          "Judgment becomes primarily about consensus-building rather than personal decision",
          "B",
          "Commander-level judgment is multi-body and multi-consequence. Unlike earlier levels where judgment operates in a more bounded context, Commander judgment must hold the whole institutional ecosystem in view."),
        q("The Service pillar at the Commander level is best exemplified by:",
          "Attendance at the most chapter events in the year",
          "Demonstrable investment in officer formation, institutional infrastructure, and the long-term health of the Order — often at personal cost and without visible credit",
          "The number of programmes the Commander personally designed and launched",
          "Fundraising totals for the period of the Commander's tenure",
          "B",
          "Commander-level service is measured by institutional investment — the officer and infrastructure development that does not produce immediate personal recognition. The board is assessing whether service is genuinely mission-oriented or performance-oriented."),
        q("The Character pillar is assessed at the Commander level primarily through:",
          "The candidate's personal statement of values",
          "Evidence of consistent character under difficulty — specifically, situations in which character cost something and was maintained anyway",
          "The candidate's reputation among those who admire him most",
          "Formal testimonials from the Major and Captain below",
          "B",
          "Character at the Commander level is evidenced by consistency under pressure, not by statements or reputation among supporters. The board will probe for situations where maintaining character carried real cost."),
        q("The Communication pillar at the Commander level includes which capability that is not required at lower ranks?",
          "The ability to write formal correspondence",
          "The ability to communicate institutional direction, rationale, and culture simultaneously to diverse audiences across multiple bodies without losing coherence or diluting substance",
          "The ability to speak at formal ceremonies",
          "The ability to give feedback in private settings",
          "B",
          "Commander-level communication must work at institutional scale — reaching diverse audiences simultaneously without losing substance or coherence. This multi-audience capacity distinguishes Commander communication from the single-body communication expected at lower ranks."),
        q("A board reviewer asks the candidate to identify the greatest weakness he has identified in himself during this programme. The best response is:",
          "To state that the programme has resolved any prior weaknesses",
          "An honest, specific identification of a genuine limitation with reflection on how the candidate has been building structures or relationships to compensate for it",
          "To identify a minor weakness that is unlikely to affect performance",
          "To reframe the question as a strength",
          "B",
          "The board is assessing self-knowledge — a Commander who cannot honestly identify and name his limitations is a dangerous candidate, because unexamined limitations become institutional vulnerabilities. Honest, specific self-assessment with a compensation strategy is the mark of a mature candidate."),
        q("A candidate Commander is asked: 'What will you do in your first 90 days?' The best answer reflects:",
          "An ambitious list of changes and new initiatives to demonstrate energy",
          "A disciplined plan centred on listening, assessing, building relationships with key officers, and understanding the current institutional state before making significant changes",
          "Continuity of predecessor programmes to demonstrate respect",
          "Immediate assertion of new strategic direction to establish leadership",
          "B",
          "The first 90 days of senior command should be built on intelligence-gathering and relationship-building, not premature initiative. Commanders who arrive with pre-built agendas often dismantle things that were working while addressing the things they assumed needed changing."),
        q("After the Commander's Board Review, whether approved or deferred, the candidate's primary obligation is to:",
          "Accept the outcome quietly and wait for the next opportunity",
          "Seek substantive feedback, integrate it honestly, and continue the formation process — because the board outcome is a point in an ongoing formation journey, not a final verdict on character",
          "Appeal any deferral decision through formal channels",
          "Assume that approval means formation is complete",
          "B",
          "The board is a formation milestone, not a terminus. Whether approved or deferred, the candidate's obligation is to extract honest learning from the review and continue growing. Treating approval as completion and deferral as rejection both miss the formative purpose of the board."),
    ]
))

COMMANDER_WEEKS = []
for i, d in enumerate(COMMANDER_WEEKS_DEF):
    title, focus, reading, terms, questions = d
    COMMANDER_WEEKS.append({
        "week_number": i + 1,
        "title": title,
        "focus": focus,
        "required_reading": reading,
        "key_terms": terms,
        "quiz_questions": questions,
        "discussion_questions": [
            "How does this week's concept reshape your understanding of senior command responsibility?",
            "Where in your current context do you see this principle most urgently needed?",
            "What would embodying this standard require you to change in your current practice?",
        ],
    })
print("Commander weeks built:", len(COMMANDER_WEEKS))
