
# ── MAJOR ─────────────────────────────────────────────────────────────────────
def _major_reading():
    return [rd("Major Syllabus","major_syllabus"),
            rd("KTKC Rules and Statutes","rules_statutes"),
            rd("KTKC Promotion Manual and By-Laws","promo_bylaws")]

MAJOR_WEEKS_DEF = []

# W1
MAJOR_WEEKS_DEF.append((
  "Week 1: The Burden of Wider Oversight",
  "Understanding the transition from local command to regional stewardship and the expanded accountability that comes with it.",
  _major_reading(),
  ["regional stewardship","wider oversight","accountability","transition","burden of command"],
  [
    q("A newly promoted Major has been overseeing two commanderies. One thrives; one struggles badly. She is tempted to concentrate almost all time on the struggling one. What is the primary danger?",
      "The thriving commandery may deteriorate without continued oversight.",
      "She signals that poor performance earns more Major attention, creating a perverse incentive.",
      "Both A and B — regional stewardship requires calibrated attention, not reactive concentration.",
      "There is no danger; a thriving commandery can run itself.",
      "C",
      "Regional oversight is not triage. Over-concentrating on the weakest unit both neglects healthy ones and teaches struggling Captains that weakness earns attention. The Major calibrates time across the region."),
    q("A Captain asks: 'What exactly is your authority over my commandery?' The most accurate answer is:",
      "Full supervisory authority — the Major can override any Captain decision.",
      "Advisory authority only — Captains lead and the Major counsels.",
      "Authority over regional standards, inter-commandery coordination, and officer accountability — but she governs through Captains, not around them.",
      "Whatever the chapter bylaws specify.",
      "C",
      "The Major governs through Captains. Her authority is real but structural — she sets and enforces regional standards and holds Captains accountable without bypassing local command."),
    q("What distinguishes regional stewardship from regional management?",
      "Stewardship implies a longer time horizon — managing for sustainability.",
      "Stewardship means holding the region in trust — responsible not just for outcomes but for formation, culture, and integrity of all bodies under her care.",
      "Stewardship is spiritual; management is operational. Both are required.",
      "There is no meaningful distinction.",
      "B",
      "Stewardship is a disposition, not a time horizon. The Major who understands herself as a steward holds the region in trust — accountable not only for what gets done but for what kind of community is being formed and what kind of officers are developing."),
    q("A Captain has been making well-intentioned promises that exceed her authority. Members are excited. The Major's first move is:",
      "Allow the promises to stand — reversing them damages morale.",
      "Correct the Captain privately, establish the boundary, and determine whether promises can be honored before any public correction.",
      "Publicly clarify the Captain's authority to reset member expectations.",
      "Report to senior leadership before taking action.",
      "B",
      "The first move is private correction. The Major clarifies the boundary with the Captain before touching member expectations. The goal is to restore right order without creating public embarrassment that undermines the Captain's future effectiveness."),
    q("Three commanderies share different cultures: formal, casual, and mixed. The Major wants to enforce a common standard. The right approach is:",
      "Require all three to adopt the same operational culture.",
      "Allow each commandery to develop freely — regional standards should not override local identity.",
      "Define non-negotiable standards for all bodies while explicitly permitting cultural variation in expression — the standard is the floor, not the ceiling.",
      "Identify the strongest culture and encourage the others to adopt it.",
      "C",
      "Standards define the floor; culture lives above it. Non-negotiable requirements apply everywhere. How those requirements are expressed can and should vary by community."),
    q("The single most disorienting aspect of the Captain-to-Major transition is:",
      "The volume of administrative work increases significantly.",
      "She no longer has one community to know deeply — she must govern across multiple bodies she cannot be fully present in.",
      "Her authority is more diffuse — she can set standards but cannot enforce them directly.",
      "She must work with Captains who may be more experienced than she is.",
      "B",
      "The most disorienting shift is the loss of deep community knowledge. A Major must govern across bodies she cannot be fully present in, relying on reports, Captain relationships, and periodic visits. Learning to lead through others is the defining challenge of the transition."),
    q("A Captain has never attended a regional meeting in four months, citing scheduling conflicts each time. The appropriate response is:",
      "Accept the conflicts and ensure meeting notes are shared.",
      "Address the absence directly — persistent non-participation in regional coordination is an accountability issue, not a scheduling problem.",
      "Require attendance at the next meeting and treat continued absence as a formal conduct issue.",
      "Survey other Captains to determine whether meetings are valuable enough to require attendance.",
      "B",
      "Persistent absence from regional coordination is an accountability issue. Four months of absence signals either disengagement or a more serious problem. The Major leads with curiosity before conclusion but does not accept the pattern passively."),
    q("What does accountability at the regional level require that local command accountability does not?",
      "Formal documentation that local command does not require.",
      "Holding Captains accountable without being able to observe their commanderies directly — relying on reported data, relationships, and periodic review.",
      "Higher stakes — errors at the Major level affect more people.",
      "More formal process — verbal feedback is insufficient at this level.",
      "B",
      "The defining challenge of regional accountability is that the Major cannot see most of what she is responsible for. She must build reliable information pipelines that give her an accurate picture of what is actually happening in each body."),
    q("The Major is frustrated that Captains implement regional standards differently. The first question she should ask herself is:",
      "Are the Captains being compliant?",
      "Are my standards clear enough that a reasonable Captain could implement them consistently?",
      "Do Captains understand the consequences of non-compliance?",
      "Should I visit each commandery personally to verify implementation?",
      "B",
      "Before concluding Captains are non-compliant, the Major examines her own clarity. Inconsistent implementation is often the product of ambiguous direction. She clarifies before she corrects."),
    q("The primary burden the Major accepts that the Captain does not is:",
      "Greater administrative complexity.",
      "Greater personal sacrifice — the Major rank requires more time and energy.",
      "Responsibility for the formation and health of communities she did not build and cannot be fully present in — stewardship of what others labored to create.",
      "Greater accountability to senior leadership.",
      "C",
      "The Major's unique burden is stewardship of the inherited. She receives commanderies she did not build, Captains she may not have developed, cultures she did not form. Her job is to receive, understand, improve, and protect.")
  ]
))

# W2
MAJOR_WEEKS_DEF.append((
  "Week 2: The Provincial Structure of the Templars",
  "Examining the historical division of the Order into provinces and the mechanics of provincial oversight.",
  _major_reading(),
  ["province","provincial master","historical structure","regional division","Templar hierarchy"],
  [
    q("The primary reason the Templar Order divided its territories into provinces was:",
      "To create competition between regional bodies.",
      "To enable centralized oversight through a single reporting structure.",
      "Because the Order spanned multiple kingdoms and legal jurisdictions, requiring local governance that could act without constant reference to central command.",
      "To limit the power of any single officer by distributing authority broadly.",
      "C",
      "The provincial structure was a practical response to geographic and jurisdictional reality. Regional leaders held real authority and could act independently within defined parameters — a structural solution to scale."),
    q("A Provincial Master's most important accountability upward covered:",
      "Financial reporting only.",
      "Military readiness only.",
      "Both financial and military reporting — the province was assessed on its ability to sustain and contribute to the Order's dual mission.",
      "Doctrinal compliance only.",
      "C",
      "Provinces existed to sustain the Order's dual mission. Provincial Masters were accountable for what they contributed and for how they governed — discipline, doctrine, formation. The Major rank inherits both dimensions."),
    q("The relationship between a Provincial Master and his commanderies was best described as:",
      "Direct administration, bypassing local Commanders.",
      "Governing through local Commanders — authority shaped the province but operated through its leaders, not around them.",
      "Advisory authority only — local Commanders were autonomous.",
      "Variable by province — some governed directly, others through deputies.",
      "B",
      "The Provincial Master's power flowed through the commandery structure. Day-to-day governance of each commandery remained with its Commander. This layered structure allowed scale without micromanagement."),
    q("Templar provincial inspections served primarily to:",
      "Identify commanderies generating insufficient revenue.",
      "Verify that the Rule was observed, military training maintained, and resources properly stewarded — ensuring the province was healthy enough to sustain the mission.",
      "Give the Provincial Master information for his annual report.",
      "Assess which commanderies deserved additional resources.",
      "B",
      "Inspections were formational, not extractive. The Provincial Master visited to assess health and correct what was out of order. The inspection was an act of care, not surveillance — the Major who understands this visits to strengthen."),
    q("The Templar Order maintained doctrinal consistency across culturally diverse provinces primarily through:",
      "Appointing Provincial Masters personally known to the Grand Master.",
      "The Rule of the Order — a common standard of life, discipline, and practice that applied everywhere, while practical adaptations were permitted for local conditions.",
      "Requiring Provincial Masters to reside at headquarters for part of each year.",
      "Traveling inspectors who reported directly to the Grand Master.",
      "B",
      "The Rule was the Order's solution to the diversity-consistency tension. It defined what was non-negotiable everywhere and permitted local adaptation in what was not essential."),
    q("The key lesson about scale and accountability from the provincial structure is:",
      "Scale inevitably weakens accountability.",
      "Scale requires layered accountability structures — each tier responsible for what it can directly observe, reporting upward so senior leaders have accurate information about what they cannot see.",
      "Scale is manageable through technology — reporting systems can substitute for presence.",
      "Strong central authority is the solution to scale.",
      "B",
      "Each tier was accountable for what it could directly know, and reliable reporting upward gave central leadership an accurate picture of the whole. The Major occupies the provincial tier."),
    q("When a Templar Provincial Master received a complaint that a local Commander was governing unjustly, the proper process was to:",
      "Investigate personally by visiting the commandery and gathering testimony from multiple members before taking action.",
      "Remove the Commander immediately — a complaint of injustice is sufficient cause.",
      "Refer the complaint to the Grand Master.",
      "Dismiss the complaint — members were not permitted to appeal over their Commander's head.",
      "A",
      "The Provincial Master's responsibility was to investigate before acting. A single complaint required verification — testimony from multiple sources, personal observation, and honest assessment. The Major applies the same principle."),
    q("What does the Templar province's eventual decline teach about governance structures?",
      "Provincial structures are inherently fragile — they depend too heavily on individual leaders.",
      "Governance structures require both material resources and clear purpose — when either fails, structure cannot compensate.",
      "The Order's decline was caused primarily by external political forces.",
      "Centralized governance is more durable than provincial governance.",
      "B",
      "The provincial structure's deterioration was a symptom of deeper failures — loss of mission clarity, political compromise, resource depletion. Governance structures channel the energy of committed people; they do not save institutions."),
    q("Studying the Templar provincial structure prepares a Major by:",
      "Providing historical precedents she can cite when justifying her authority.",
      "Showing that the structures she inhabits are not arbitrary — they were forged through centuries of effort to solve the real problem of governing a dispersed body with a unified mission.",
      "Providing specific administrative techniques she can adopt directly.",
      "Reminding her that even well-designed structures eventually fail.",
      "B",
      "Historical study is orientation, not nostalgia. The Major who understands where her role comes from sees that her responsibilities were worked out over centuries by people who faced the same basic problem."),
    q("The most important single lesson from the Templar provincial model is:",
      "Visit frequently — physical presence is the Provincial Master's most powerful accountability tool.",
      "The province exists for the mission, not for its own perpetuation — provincial structure is a means, not an end, and every structural decision should be evaluated against whether it serves the Order's purpose.",
      "Clarity of standards is the Provincial Master's most important contribution.",
      "The Provincial Master's authority must be exercised decisively — a Major who does not use her authority loses it.",
      "B",
      "The Templar province existed to advance the mission — not to create careers or perpetuate structure. When the provincial structure served the mission, it was healthy. The Major governs structures relentlessly in service of why the Order exists.")
  ]
))

# W3
MAJOR_WEEKS_DEF.append((
  "Week 3: The Office of Provincial Master / Grand Prior",
  "The historical role, administrative authority, and operational duties of the Provincial Master.",
  _major_reading(),
  ["Provincial Master","Grand Prior","officer duties","administrative authority","historical office"],
  [
    q("The two distinct types of authority the Provincial Master held were:",
      "Executive authority and legislative authority.",
      "Administrative authority (governance of people and resources) and operational authority (direction of mission activities).",
      "Formal authority (granted by the Grand Master) and informal authority (earned through personal respect).",
      "Internal authority (over the province) and external authority (representing the Order to civil powers).",
      "B",
      "The Provincial Master governed on two axes: administrative and operational. The Major who understands these as distinct responsibilities governs more deliberately, ensuring neither crowds out the other."),
    q("The standard that guided Provincial Master appointments and removals of Commanders was:",
      "Seniority — the most experienced knight in a commandery was typically appointed.",
      "Merit and fitness for the office — could the candidate fulfill the Commander's specific responsibilities effectively and with integrity?",
      "Central direction — the Grand Master made all appointments.",
      "Election — commandery members had input and the Provincial Master ratified.",
      "B",
      "Appointments were governed by fitness for the office. Seniority was relevant context but not the criterion. The Major inherits this standard: who is the right person for this role, now, given what this community needs?"),
    q("What distinguished the Grand Prior from a standard Provincial Master?",
      "The Grand Prior had authority over multiple provinces.",
      "The Grand Prior held a more specifically ecclesiastical or ceremonial role, while the Provincial Master focused on administrative and military governance.",
      "The Grand Prior was appointed for life.",
      "The distinction was primarily honorific.",
      "B",
      "The Grand Prior role emphasized the Order's religious character — oversight of spiritual and ceremonial life — while the Provincial Master role emphasized governance and operational command. The Major who understands herself as both administrator and formational steward is closer to the Grand Prior model."),
    q("How did the Provincial Master balance his province's internal life against accountability to central command?",
      "He prioritized central command — the Grand Master's directives superseded local needs.",
      "He prioritized local needs — the province's health was primary.",
      "He maintained both — governing with genuine care for the province's health while fulfilling reporting and contribution obligations, and flagging honestly when central directives created impossible local conditions.",
      "He managed tension through delegation — he handled central obligations while lieutenants managed internal affairs.",
      "C",
      "The Provincial Master served two masters — the Order's central mission and the province's local health. Faithfulness to the center without sensitivity to local reality produces harm. Exclusive focus on local needs without accountability to the larger Order produces insularity."),
    q("The Provincial Master's responsibility regarding the Rule of the Order was to:",
      "Interpret the Rule for his province.",
      "Enforce the Rule as written with no latitude for local interpretation.",
      "Ensure the Rule was known, understood, and observed in all commanderies — and correct departures firmly and promptly.",
      "Report violations to central command for adjudication.",
      "C",
      "The Provincial Master was the guardian of the Rule within his province. His responsibility was to know it, teach it, and correct breaches directly and promptly."),
    q("Provincial chapters — gatherings of local Commanders — served primarily to:",
      "Report provincial performance to the Grand Master.",
      "Coordinate across commanderies, resolve conflicts, share resources, and ensure all Commanders understood provincial standards and expectations.",
      "Provide Commanders with continuing education.",
      "Allow Commanders to bring grievances directly to the Provincial Master.",
      "B",
      "Provincial chapters were coordination events. The Major who convenes regular regional gatherings for her Captains is operating in this tradition — creating the forum where the region can think and act as a coherent body."),
    q("When two Commanders had a serious resource dispute that damaged their relationship, the Provincial Master was expected to:",
      "Adjudicate and issue a binding decision.",
      "Refer the dispute to the Grand Master.",
      "Facilitate reconciliation before adjudication — the goal was restoration of the relationship, not just resolution of the specific dispute.",
      "Divide the resources equally and require both to accept.",
      "C",
      "Restoration was the goal. The Provincial Master who resolved the dispute but left the relationship broken accomplished only half the task. The Major aims for the same: resolve the presenting issue and restore the working relationship."),
    q("The personal qualities considered most essential for a Provincial Master were:",
      "Intelligence and strategic vision.",
      "Justice, prudence, and personal integrity — qualities that made a man trustworthy to govern others faithfully on behalf of the Order.",
      "Military experience and personal courage.",
      "Administrative competence and attention to detail.",
      "B",
      "The Templar tradition consistently elevated character over competence for high office. Justice, prudence, and personal integrity were the marks of a man worthy of governing others. The Major who cultivates these operates in the same tradition."),
    q("How should the Major understand the historical Provincial Master's role relative to her own?",
      "As a direct model to be replicated.",
      "As a historical precedent that illuminates the meaning of her role — not to be replicated in every detail, but understood as the tradition she inhabits.",
      "As an aspirational ideal.",
      "As interesting background history, but not directly relevant to practical responsibilities.",
      "B",
      "The Major inhabits a tradition. The Provincial Master's role is not a blueprint but a lineage — it reveals what this kind of responsibility has meant for people who took it seriously over centuries."),
    q("The ultimate test of a Provincial Master's success was:",
      "Whether his province consistently met financial and military contribution obligations.",
      "Whether his province was better — stronger in discipline, formation, and mission capacity — when he left it than when he received it.",
      "Whether his Commanders respected and followed him without conflict.",
      "Whether central command regarded his province as a model for others.",
      "B",
      "The Provincial Master's ultimate test was the condition of the province at the end of his tenure. A province that maintained stability was managed; a province that became more capable was led. The Major governs with an eye on what she is leaving.")
  ]
))

# W4
MAJOR_WEEKS_DEF.append((
  "Week 4: Mission Alignment Across Multiple Bodies",
  "Unifying diverse local commanderies under a single operational standard and core mission.",
  _major_reading(),
  ["mission alignment","operational standard","unified mission","diversity","coordination"],
  [
    q("Two commanderies understand the Order's mission very differently — one emphasizes service, one formation. Both are active and healthy. The Major should:",
      "Correct both toward a single, authoritative interpretation.",
      "Allow each to pursue its own emphasis — diversity enriches the region.",
      "Facilitate a regional conversation clarifying that service and formation are complementary rather than competing, and ensure both commanderies pursue both dimensions.",
      "Ask central leadership for an authoritative mission statement.",
      "C",
      "Service and formation are both essential. The Major's task is to show they belong together — that service without formation is activism, and formation without service is self-cultivation."),
    q("Mission alignment differs from mission uniformity in that:",
      "Alignment means all bodies pursue the same goal; uniformity means they pursue it the same way. Alignment is required; uniformity is not.",
      "Alignment is an aspiration; uniformity is a requirement.",
      "They are the same — consistent mission execution requires both.",
      "Alignment applies to goals; uniformity applies to methods. The Major governs methods, not goals.",
      "A",
      "The Major requires alignment — all commanderies pursuing the same core mission — but does not require uniformity of expression, style, or program. A rural commandery and an urban one will pursue the same mission very differently."),
    q("The most effective way to communicate regional mission priorities to Captains is:",
      "Send a detailed written directive specifying priorities, activities, and reporting requirements.",
      "Convene a regional meeting where she articulates priorities, invites Captain input on local pursuit, and establishes shared understanding through conversation.",
      "Visit each commandery personally and repeat the same message, tailoring language to local community.",
      "Ask each Captain to derive mission priorities from governing documents independently, then compare conclusions.",
      "B",
      "Mission alignment is a relational and conversational achievement. Captains who help shape how priorities are expressed locally are far more likely to pursue them genuinely than Captains who receive mandates."),
    q("A commandery with a strong local identity resists regional direction. The right first step is:",
      "Assert authority clearly — resistance is a compliance issue.",
      "Investigate first: is the resistance genuine local wisdom about what works in that community, or is it insularity and defensiveness? The response depends on the diagnosis.",
      "Work through the Captain to gradually introduce expectations, building trust before pressing for compliance.",
      "Exempt the commandery temporarily.",
      "B",
      "Strong local identity is not automatically problematic. The Major's first question is diagnostic. If the commandery has genuinely effective local practices, the resistance may contain wisdom. If it is insularity that prevents the community from receiving what it needs, it requires correction."),
    q("Shared language in mission alignment matters because:",
      "It is a secondary concern — alignment is achieved through shared action, not shared vocabulary.",
      "When commanderies use different words for the same things, they cannot coordinate effectively, and vocabulary differences often signal deeper understanding differences.",
      "It can become a substitute for genuine alignment — the Major should focus on observable behavior.",
      "Its value depends on whether it is backed by genuine shared understanding.",
      "D",
      "Shared language matters as a signal of shared understanding — but the Major who stops at vocabulary without verifying shared meaning has accomplished very little. Shared language is a starting point."),
    q("A commandery consistently produces excellent results by unusual methods. The Major's response is to:",
      "Require alignment with regional standards — consistency matters more.",
      "Study what the commandery is doing, understand why it works, and consider whether methods should be shared regionally or adopted as a regional standard.",
      "Give the commandery freedom and let others observe organically.",
      "Report the methods to senior leadership for potential Order-wide adoption.",
      "B",
      "Excellence is information. The Major who observes consistent results from unusual methods has an obligation to understand them — what is working, why, and whether it is replicable in other contexts."),
    q("The best way to ensure mission alignment persists through commandery leadership transitions is:",
      "Documenting regional standards thoroughly so incoming Captains have clear written guidance.",
      "Building formation into the transition process — briefing incoming Captains on regional culture, standards, and expectations personally, not just through documents.",
      "Requiring overlap periods between outgoing and incoming Captains.",
      "Conducting post-transition assessments six months after a Captain change.",
      "B",
      "Documentation preserves information; personal formation preserves culture. The Major who briefs incoming Captains personally builds alignment into the person, not just the paper."),
    q("A newly formed commandery has no established culture yet. The most important guidance to the founding Captain is:",
      "Model the culture you want from the first meeting — culture is established by what leaders do, not what they say.",
      "Write a community charter that articulates values, expectations, and mission before the first gathering.",
      "Connect the founding community to the region's most established commandery.",
      "Focus the first year entirely on formation — culture cannot be established until members are individually formed.",
      "A",
      "Culture is established by behavior, not documents. The founding Captain who from the first meeting models the discipline, care, accountability, and mission focus she wants will produce a community that reflects those qualities."),
    q("Mission alignment at its best in a healthy region looks like:",
      "All commanderies pursue identical programs and activities.",
      "Commanderies pursue the same core mission with genuine conviction, express it in culturally appropriate ways, support each other across boundaries, and can articulate clearly why they do what they do.",
      "Captains defer to regional direction without friction, implementing priorities efficiently.",
      "The region produces measurable results demonstrating operational health.",
      "B",
      "Mission alignment at its best is shared conviction, not compliance. The commanderies that are genuinely aligned pursue the mission because they understand and believe in it, not because the Major is watching."),
    q("Mission alignment is harder to maintain at the regional level because:",
      "The Major has less authority than a Captain — she governs through others and cannot enforce alignment directly.",
      "The Major cannot be fully present in each commandery — she must build alignment through relationships, structures, and formation rather than direct daily presence.",
      "Regional standards are necessarily more abstract, making them harder to apply consistently.",
      "Captains are more resistant to external direction than members are to Captain direction.",
      "B",
      "The Major's alignment challenge is fundamentally one of presence. Local alignment is maintained partly through the Captain's constant presence; regional alignment must be maintained through structures and formation that operate in the Captain's absence.")
  ]
))

# W5
MAJOR_WEEKS_DEF.append((
  "Week 5: Inspection, Accountability, and Standards",
  "Establishing accountability, maintaining strict standards, and conducting regional inspections effectively.",
  _major_reading(),
  ["inspection","accountability","standards","review process","corrective action"],
  [
    q("A Major is preparing to inspect a commandery for the first time. To ensure the inspection is genuinely useful rather than a performance, she should:",
      "Announce the visit well in advance so the commandery can prepare.",
      "Conduct the visit unannounced.",
      "Announce the visit but explicitly frame it as: she wants to see how the commandery normally operates, including its real challenges.",
      "Ask the Captain to prepare a self-assessment first, then use the visit to verify.",
      "C",
      "The Major who announces a visit and frames it as a performance audit will observe a performance. Explicitly saying 'show me how you actually work' is more likely to reveal the real condition."),
    q("During an inspection, the Major observes a practice that may violate regional standards. The Captain seems unaware. The right move is:",
      "Note it privately and address it in a written follow-up after the inspection.",
      "Ask about it directly during the inspection — name what she observed, describe the concern, and invite the Captain's explanation before drawing conclusions.",
      "Report the observation to senior leadership before addressing it with the Captain.",
      "Address it with the Captain's team directly, since the Captain may be too close to see the problem.",
      "B",
      "The Major names what she sees and asks directly. Silence during inspection and documentation afterward is a form of ambush. Asking directly is both more honest and more instructive — the Captain learns what the Major is looking for and why."),
    q("The difference between a standard and a goal is:",
      "Standards are minimums; goals are aspirations. Both are important and should not be confused.",
      "Standards are externally defined; goals are internally chosen.",
      "Standards are permanent; goals are time-bound.",
      "There is no meaningful distinction.",
      "A",
      "Standards define the floor — what every commandery must do, always. Goals describe aspirations. Treating a goal as a standard creates impossible requirements; treating a standard as a goal makes basics optional."),
    q("A Captain argues a regional standard is unrealistic for her commandery's size and resources. The Major's response is to:",
      "Enforce the standard — a standard that varies by circumstance is not a standard.",
      "Exempt the commandery.",
      "Investigate: is the standard genuinely unrealistic for this context, or is the Captain seeking to avoid accountability? If miscalibrated, revise it; if not, support the Captain in meeting it.",
      "Escalate to senior leadership for a ruling.",
      "C",
      "Standards that are genuinely miscalibrated should be revised — maintaining an unrealistic standard damages credibility. But the investigation must be honest: some standards that feel unrealistic are simply demanding, and the Captain's real need is support, not exemption."),
    q("The right inspection frequency for commanderies is:",
      "Annually at minimum, with additional visits triggered by concerning reports or significant transitions.",
      "Quarterly — regular inspection is the only way to maintain accountability.",
      "As needed — inspection frequency should be driven by commandery performance.",
      "Twice a year.",
      "A",
      "Annual inspection is the minimum; circumstances may require more. The fixed annual inspection signals that oversight is normal and expected; responsive additional visits signal that the Major is paying attention."),
    q("A commandery is 60 days into a 90-day improvement plan. The Captain reports progress is on track. The Major should:",
      "Accept the Captain's report and wait for the 90-day review.",
      "Verify the progress independently — schedule a check-in or request specific observable evidence rather than relying solely on the Captain's self-assessment.",
      "Ask the Captain to submit a written progress report with documentation.",
      "Trust the Captain's judgment.",
      "B",
      "Accountability structures work only when they include verification. The Major who sets an improvement plan and then accepts self-reports without independent verification has created a loop where the person being held accountable is also the judge of her own progress."),
    q("The most common way regional standards erode over time is:",
      "Standards erode when not documented — verbal standards are forgotten.",
      "Standards erode through selective enforcement — as exceptions accumulate, the standard gradually becomes the exception.",
      "Standards erode when leadership transitions occur.",
      "Standards erode through cultural drift.",
      "B",
      "Selective enforcement is the most reliable path to standard erosion. Each exception seems reasonable in isolation. Accumulated over time, exceptions signal the standard is negotiable — which means it effectively is not a standard."),
    q("A commandery meets the letter of every regional standard but clearly not the spirit — technically compliant, substantively hollow. The Major's responsibility is:",
      "Accept the technical compliance — she can only hold commanderies to what is written.",
      "Name what she observes clearly and directly — 'you are meeting the standard in form but not in substance' — and work with the Captain to understand what is driving the hollowness.",
      "Revise the standards to close the gaps.",
      "Escalate to senior leadership.",
      "B",
      "Technical compliance without genuine engagement signals something — disconnection from mission, disillusionment, exhaustion, or loss of conviction. The Major names what she sees and investigates honestly."),
    q("A Captain consistently produces excellent results and meets all standards. The Major is tempted to reduce oversight. She should:",
      "Yes — excellent performance is evidence oversight can be safely reduced.",
      "No — consistent performance can mask deterioration visible only when standards lapse.",
      "Partially — reduce formal inspection frequency but maintain regular communication and remain available.",
      "It depends on the Captain's tenure.",
      "C",
      "Excellent performance earns adjusted oversight, not eliminated oversight. The Major reduces inspection frequency for excellent commanderies but does not disappear. Regular communication and periodic formal review remain."),
    q("The relationship between accountability and trust in regional governance is:",
      "Inversely related — high trust means low accountability requirements.",
      "Complementary — accountability structures create the conditions under which trust can be extended responsibly, and trust creates the environment within which accountability is received honestly.",
      "Accountability is a substitute for trust.",
      "Trust is the goal; accountability is the mechanism — as trust develops, accountability requirements should decrease.",
      "B",
      "Trust and accountability are not opposites. The Major who builds genuine relationships creates a context in which accountability conversations can be direct without being threatening. High trust and high accountability together produce the best regional outcomes.")
  ]
))

# W6
MAJOR_WEEKS_DEF.append((
  "Week 6: Recruitment, Growth, and Officer Pipeline",
  "Sustaining the Order through strategic recruitment and building a capable pipeline of future officers.",
  _major_reading(),
  ["recruitment","officer pipeline","growth","succession planning","formation pipeline"],
  [
    q("Commanderies consistently struggle to find members willing to enter officer formation. The most likely systemic cause is:",
      "The formation programs are too demanding.",
      "Members are not being invited — the pipeline requires that someone actively identify candidates and extend a personal invitation.",
      "The commanderies are too small.",
      "Officer formation is not being visibly valued — if members do not see officers being developed and honored, they do not aspire to the path.",
      "D",
      "Pipeline problems are almost always culture problems before structural ones. When members do not aspire to officer formation, it is typically because they do not see it as worth pursuing."),
    q("Recruitment differs from growth in that:",
      "Recruitment brings in new members; growth develops existing members.",
      "Recruitment is tactical (finding and inviting specific people); growth is strategic (the community becoming larger and stronger in mission capacity). Both require active cultivation.",
      "Recruitment is the Captain's responsibility; growth is the Major's.",
      "There is no meaningful distinction.",
      "B",
      "Recruitment without formation produces numbers without capacity. Growth in numbers without growth in mission depth produces a larger but shallower community."),
    q("A commandery has grown significantly in membership but developed no new officer candidates. The Captain attributes this to the quality of incoming members. The Major should:",
      "Accept the Captain's assessment.",
      "Investigate whether the commandery's formation pathway is actually developing people or just processing them — growth without officer candidates is a formation failure, not a membership quality problem.",
      "Assist the Captain in identifying specific members who show officer potential.",
      "Require the commandery to submit a formal officer development plan.",
      "B",
      "Blaming member quality is almost never the real explanation. The formation pathway either develops people or it does not. A commandery that grows in numbers but produces no officer candidates has a formation problem."),
    q("The best structure for building a regional officer pipeline that does not depend entirely on individual Captains identifying candidates is:",
      "A regional nomination process where members can self-nominate.",
      "A regional formation cohort — a structured pathway that identifies and develops officer candidates across commanderies, giving the Major visibility into the pipeline above the commandery level.",
      "A regional mentorship network pairing experienced officers with promising members across commandery boundaries.",
      "An annual regional leadership conference where candidates are identified through participation.",
      "B",
      "A regional formation cohort gives the Major structural visibility into the pipeline without depending on each Captain's judgment. It also creates cross-commandery relationships among emerging officers."),
    q("The most common failure mode in succession planning for commandery leadership is:",
      "Planning too far in advance.",
      "Planning too late — succession planning begins only when a Captain announces her departure.",
      "Identifying successors based on who is available rather than who is best formed.",
      "Both B and C — late planning and low-quality identification often occur together.",
      "D",
      "Succession planning failures are almost always failures of timing and standard. Planning begins at departure announcement, leaving weeks instead of years. Because time is short, the choice defaults to whoever is available."),
    q("A Captain resists developing a clear successor, preferring not to think about her departure while still effective. The Major should:",
      "Respect the preference.",
      "Frame succession planning as care for the commandery, not preparation for the Captain's departure — she is building community resilience, not planning her exit.",
      "Require a formal succession plan as part of annual reporting.",
      "Identify a potential successor independently and begin developing that person without the Captain's involvement.",
      "B",
      "The Major reframes: succession planning is not about the Captain leaving — it is about the community being strong enough to handle leadership transition without crisis."),
    q("Regional recruitment strategy differs from commandery recruitment strategy in that:",
      "Regional strategy focuses on the Order's external reputation; commandery strategy focuses on member experience.",
      "Regional strategy identifies and cultivates relationships with organizations and communities that may produce members across multiple commanderies; commandery strategy focuses on specific individuals.",
      "Regional strategy is driven by the Major; commandery strategy by the Captain. They should not overlap.",
      "There is no meaningful strategic difference.",
      "B",
      "The Major can identify institutional partnerships that create a pipeline across multiple commanderies. Individual relationship-based recruitment remains the Captain's primary tool. The Major amplifies the regional pipeline in ways individual commanderies cannot."),
    q("The Major knows most of the region's growth is concentrated in one commandery while three others are stagnant. Senior leadership tells her the numbers look excellent. She should:",
      "Report aggregate numbers honestly — accurate reporting is the Major's obligation.",
      "Report aggregate numbers but add context — the distribution of growth matters as much as the total.",
      "Hold the report until she has investigated whether stagnant commanderies can be improved.",
      "Focus energy on stagnant commanderies and let the growing one continue.",
      "B",
      "Aggregate numbers can hide regional health problems. The Major who adds context gives leadership genuinely useful information. Reporting numbers without context the Major knows matters is information management, not honest reporting."),
    q("The relationship between individual formation and officer pipeline health is:",
      "Separate concerns — pipeline health depends on structural factors.",
      "Deep individual formation is the upstream cause of pipeline health — commanderies that form members well produce people who want to serve.",
      "Individual formation is necessary but not sufficient — pipeline health also requires active identification and invitation.",
      "Pipeline health depends primarily on program visibility and accessibility.",
      "B",
      "Formation is the root of pipeline health. Commanderies that form members deeply produce people who want to take on greater responsibility. The pipeline problem is almost always a formation problem."),
    q("The Major's personal responsibility in the officer pipeline is:",
      "Managing the regional pipeline — tracking candidates and ensuring the region has sufficient depth.",
      "Developing Captains who develop others — the Major's most important pipeline contribution.",
      "Identifying promising candidates personally and investing in their formation directly.",
      "Both A and B — the Major both manages the pipeline and develops Captains who contribute to it.",
      "D",
      "The Major's pipeline responsibility is both structural and formational. A Major who only manages the pipeline without developing Captains who develop others will always be the bottleneck.")
  ]
))

# W7
MAJOR_WEEKS_DEF.append((
  "Week 7: Resource Stewardship and Regional Planning",
  "Managing regional assets, prioritizing resources, and planning for the long-term health of the province.",
  _major_reading(),
  ["resource stewardship","regional planning","budget","asset management","long-term thinking"],
  [
    q("Limited discretionary resources; three commanderies requesting support — large/thriving, mid-sized/growing, small/struggling. The right allocation basis is:",
      "Proportionally by size.",
      "To the struggling commandery — need should drive allocation.",
      "Based on projected return — invest where resources will produce the greatest regional impact, requiring honest assessment of each commandery's capacity to use resources effectively.",
      "Equally — fairness requires the same baseline support.",
      "C",
      "Resource stewardship requires honest impact assessment. Equal distribution ignores capacity differences. Need-based distribution can entrench dependency. The Major asks: where will this investment produce the most regional good?"),
    q("Short-term tactical planning differs from long-term strategic planning in that:",
      "Tactical planning addresses specific problems; strategic planning addresses the region's overall direction.",
      "Tactical planning operates within the current year; strategic planning extends three to five years.",
      "Tactical planning is the Captain's domain; strategic planning is the Major's.",
      "There is no meaningful distinction — all planning at this level should be strategic.",
      "A",
      "Both are necessary and distinct. Tactical planning solves current problems. Strategic planning asks what the region needs to become and what decisions must be made now. The Major who only plans tactically is always fighting fires."),
    q("A Captain argues her commandery budget should increase because she has ambitious plans. The deciding factor should be:",
      "The Captain's track record.",
      "The plan's quality — ambitious plans backed by clear logic deserve investment.",
      "Both A and B — past performance and plan quality together form the basis for investment decisions.",
      "Regional priority — individual Captains' ambitions are secondary.",
      "C",
      "Sound resource allocation combines track record and plan quality. Past performance alone is insufficient; plan quality alone is insufficient. The combination — a capable Captain with a sound plan that advances regional priorities — is the right investment."),
    q("Asset management at the regional level means:",
      "Managing financial assets — accounts, funds, and investments.",
      "Managing all resources entrusted to the region — including people, relationships, institutional knowledge, physical assets, and financial resources — as a faithful steward rather than an owner.",
      "Ensuring commandery assets are properly documented and protected.",
      "Overseeing physical facilities and equipment used by commanderies.",
      "B",
      "The Major's most important regional assets are often relational and human — trust between the Major and her Captains, institutional knowledge held by long-tenured officers, community relationships that enable the mission."),
    q("A regional initiative the Major invested significant resources in clearly failed — no meaningful results, time and money consumed. The right response is:",
      "Minimize discussion to protect regional morale and the Major's credibility.",
      "Conduct an honest after-action review, understand why the initiative failed, apply the lessons to future planning, and communicate the outcome honestly to relevant stakeholders.",
      "Assign responsibility for the failure to the Captain who led the initiative.",
      "Reframe the failure as a learning investment and highlight secondary benefits.",
      "B",
      "Failure is information. The Major who conducts an honest after-action review builds a regional culture of honest assessment and continuous improvement. The Major who minimizes, assigns blame, or reframes builds a culture where people hide problems."),
    q("For significant regional changes — leadership transitions, new commandery formation, major programs — planning should begin:",
      "One year in advance.",
      "Two to three years in advance — significant changes require enough lead time to develop the people and structures that will carry them.",
      "As far in advance as relevant information is available.",
      "Six months in advance.",
      "B",
      "Significant changes require long lead times because people development is the most time-consuming element. A new commandery needs a formed founding Captain — which requires two or three years of development before the founding."),
    q("A Captain requests regional resources for a program that does not align with regional priorities. The Major should:",
      "Provide the resources — local demand is a valid basis.",
      "Decline — regional resources fund regional priorities.",
      "Decline the resource request but support the Captain in pursuing the program with local resources if she chooses.",
      "Ask the Captain to revise the proposal to align with regional priorities.",
      "C",
      "The Major respects local initiative while maintaining regional resource discipline. Regional resources fund regional priorities. The Major who says 'yes to the program, no to the regional funding' preserves both the Captain's initiative and budget integrity."),
    q("The most important thing a Major can do to ensure regional financial health is:",
      "Maintain a strong reserve fund.",
      "Build financial literacy into officer formation so Captains manage commandery finances competently.",
      "Establish clear financial reporting requirements so the Major has an accurate picture of regional health.",
      "All of the above — regional financial health requires reserves, capable officers, and accurate information.",
      "D",
      "Regional financial health is the product of multiple interdependent factors. Reserves provide resilience. Capable Captains prevent commandery-level failures from becoming regional crises. Accurate reporting enables proactive management."),
    q("The Major is asked to present the region's five-year plan but has not developed a genuine one due to focus on operational challenges. She should:",
      "Present her best current thinking, framing it honestly as a draft requiring further development.",
      "Decline to present until she has developed a real plan.",
      "Ask a Captain with strategic planning experience to help develop the plan before presentation.",
      "Present current operational priorities and explain the five-year horizon is under development.",
      "A",
      "Honest presentation of work-in-progress is preferable to both delay and performance. The Major who presents her current thinking clearly and commits to further work demonstrates intellectual honesty and genuine engagement."),
    q("What distinguishes a Major who manages resources from one who stewards them?",
      "Managing is short-term; stewardship is long-term.",
      "Managing focuses on efficiency; stewardship focuses on faithfulness to purpose.",
      "A steward holds resources in trust and governs them with accountability to the mission and to those who entrusted her — a manager governs for operational effectiveness without the same sense of accountability.",
      "There is no meaningful distinction — good management is faithful stewardship.",
      "C",
      "Stewardship is a disposition. The Major who understands herself as a steward knows the resources she governs are not hers — they belong to the mission and the community. She is accountable not just for efficiency but for faithfulness.")
  ]
))

# W8
MAJOR_WEEKS_DEF.append((
  "Week 8: Training Captains and Strengthening Local Command",
  "Mentoring local Captains to ensure their commanderies are strong, independent, and well-led.",
  _major_reading(),
  ["Captain mentoring","local command","officer development","training","independence"],
  [
    q("A new Captain struggles with delegation — she handles every task personally because it is faster and more reliable. The Major's best first move is:",
      "Let the Captain learn through experience.",
      "Name the pattern directly: 'I've noticed you tend to handle things personally. What is driving that?' Then work through the root cause together.",
      "Assign a delegation exercise — require her to delegate three tasks in the next month.",
      "Connect the Captain with a more experienced peer who worked through the same challenge.",
      "B",
      "The Major names what she observes and asks about the root cause before prescribing a solution. Delegation resistance usually comes from specific fears. Understanding which fear is driving the pattern is necessary before the right support can be offered."),
    q("A Captain is technically competent but interpersonally avoidant — she handles tasks well but avoids difficult conversations. The most important thing the Major can do is:",
      "Remove her from situations requiring difficult conversations.",
      "Provide direct feedback that the avoidance is a gap in her command capability, and work with her on a concrete plan for building that skill.",
      "Give her lower-stakes interpersonal situations to practice in.",
      "Accept the limitation — some leaders are task-oriented.",
      "B",
      "Interpersonal avoidance at the command level is not a stylistic preference — it is a leadership gap. The Captain who cannot hold difficult conversations cannot hold people accountable or address real community problems."),
    q("A Captain asks advice on a disruptive longtime member and seems to be looking for validation of a decision she has already made. The Major's best response is:",
      "Validate the Captain's decision.",
      "Ask questions that surface whether the Captain has considered all relevant factors before confirming or redirecting her thinking.",
      "Give the advice the Captain is seeking — the Major's role is to support Captain confidence.",
      "Redirect the Captain to handle it independently.",
      "B",
      "The Major's advice is most valuable when genuinely tested. She asks: What have you tried? What is the member saying? What outcome are you hoping for? These questions may reveal unconsidered factors — or confirm the Captain's judgment is sound."),
    q("The risk of the Major solving commandery problems directly rather than developing the Captain's capacity is:",
      "It creates resentment.",
      "It creates dependency — the commandery learns to wait for Major intervention.",
      "It sets a precedent — every Captain will expect the same level of intervention.",
      "All of the above.",
      "D",
      "The Major who solves commandery problems directly invests in the short term at the expense of the long term. The commandery learns dependency, the Captain loses a development opportunity, and every other Captain notices."),
    q("A Captain has been in her role two years and is clearly ready for greater responsibility but has not expressed interest in advancement. The Major should:",
      "Respect the apparent preference.",
      "Ask directly: 'Have you thought about what comes after this role? I think you have capacity that goes beyond what you're currently using.' Open the conversation explicitly.",
      "Nominate the Captain for advancement regardless of expressed preference.",
      "Assign regional responsibilities that extend beyond her commandery.",
      "B",
      "Many capable leaders do not self-nominate — they wait to be invited. The Major's responsibility is to name what she sees and open the door."),
    q("The Major develops Captains differently from how a Captain develops members because:",
      "The Major focuses on leadership concepts; the Captain focuses on practical skills.",
      "The Captain develops members into capable contributors; the Major develops Captains into capable, independent leaders who can develop others — adding the meta-level of multiplied investment.",
      "The Major uses more formal processes where the Captain uses more relational and organic approaches.",
      "The development is fundamentally the same.",
      "B",
      "The Major's development work operates at the meta-level: she is not just forming a person but forming a person who forms people. That multiplied return is why developing Captains who develop others is the Major's most important long-term contribution."),
    q("A Major has five Captains: two excellent, two adequate, one clearly struggling. The right allocation of development attention is:",
      "Focus on the struggling Captain.",
      "Focus on the excellent Captains.",
      "Differentiate: intensive support for the struggling Captain, strategic investment in the excellent ones, adequate oversight for the adequate ones.",
      "Allocate equal time — fairness requires consistent attention.",
      "C",
      "Development attention should be differentiated. The struggling Captain needs intensive support. The excellent Captains are ready for stretch investment. Treating all five identically fails all of them."),
    q("A Captain has received the same feedback from the Major three times over six months and has not changed her behavior. The Major should:",
      "Accept that this Captain has reached the limit of her development.",
      "Deliver the feedback more directly — name that this is the third time, describe the pattern clearly, and explain the consequence if the behavior does not change.",
      "Involve senior leadership — repeated non-response requires escalation.",
      "Change the approach — if three repetitions have not produced change, the feedback method is not working.",
      "B",
      "Repeated feedback without change requires escalation in directness, not persistence in the same approach. The Major names the pattern clearly and makes plain that continued non-response is a performance concern."),
    q("What distinguishes a Major who coaches Captains from one who merely directs them?",
      "Coaching involves questions; directing involves answers.",
      "Coaching builds internal capacity; directing produces compliance.",
      "Coaching is more time-intensive and should be reserved for high-potential Captains.",
      "Both A and B — coaching is question-based and builds internal capacity simultaneously.",
      "D",
      "Coaching is both methodologically different (more questions, fewer answers) and purposively different (building internal capacity rather than producing compliance). The directing Major produces Captains who need her; the coaching Major produces Captains who eventually don't."),
    q("The ultimate goal of the Major's investment in her Captains is:",
      "To produce Captains who meet regional standards consistently.",
      "To produce Captains capable of governing their commanderies without ongoing Major oversight — who have been formed well enough to be genuinely independent.",
      "To produce Captains ready for advancement to the Major rank.",
      "To produce Captains who share the Major's values and approach.",
      "B",
      "The Major's formation investment culminates in genuine independence. The Captain who has been well developed can govern without constant consultation, make sound decisions in novel situations, and develop her own officers from a position of genuine strength.")
  ]
))

# W9
MAJOR_WEEKS_DEF.append((
  "Week 9: Communication, Coordination, and Order",
  "Developing clear protocols for region-wide communication, reporting, and logistical coordination.",
  _major_reading(),
  ["communication protocols","reporting","coordination","information flow","regional communication"],
  [
    q("Important regional information consistently arrives late at some commanderies and not at all at others. The systemic issue and right address is:",
      "Reliability — Captains are not prioritizing communication. Require acknowledgment receipts.",
      "Channel inconsistency — different commanderies use different methods. Standardize a single channel.",
      "Structure — there is no reliable protocol. Design and implement a clear communication protocol with defined channels, timing, and responsibilities.",
      "Trust — disengaged Captains deprioritize incoming communication. Rebuild relational engagement first.",
      "C",
      "Communication failures are almost always structural before they are motivational. When information arrives inconsistently, the problem is the absence of a reliable protocol. Structural solutions are more durable than motivational ones."),
    q("Information flow differs from communication in that:",
      "Information flow is one-directional; communication is two-directional.",
      "Information flow is the movement of data and directives; communication is the relational exchange through which meaning is built, concerns are raised, and understanding is verified.",
      "Information flow is the Major's responsibility; communication is the Captain's.",
      "There is no meaningful distinction.",
      "B",
      "Information flow can operate without communication — directives can be transmitted without anyone checking whether they were understood. The region that has information flow but not communication has a bulletin board, not a leadership culture."),
    q("The Major holds monthly regional calls but Captains participate minimally — they answer questions but rarely volunteer information or raise concerns. The most likely cause is:",
      "The calls are too frequent.",
      "The Captains do not feel safe raising concerns — the meeting culture signals the Major's role is to assess, not to collaborate.",
      "The Captains are too busy with local concerns.",
      "The format is wrong — calls without visual connection produce lower engagement.",
      "B",
      "Minimal participation is almost always a psychological safety issue. When Captains answer questions but do not volunteer concerns, they are signal-reading: the meeting is an assessment event, not a collaborative one."),
    q("A Captain consistently over-reports — sending lengthy detailed updates that consume significant Major time but rarely contain actionable information. The best response is:",
      "Receive the reports without comment — over-reporting is preferable to under-reporting.",
      "Work with the Captain to design a reporting template that captures key information efficiently, addressing both the Captain's apparent anxiety and the Major's time constraints.",
      "Ask the Captain to reduce report length and frequency.",
      "Accept the pattern — some Captains communicate in detail as a feature of their governance style.",
      "B",
      "Over-reporting is often driven by anxiety — the Captain is not sure what the Major needs, so she sends everything. Designing a clear reporting template solves both problems: the Captain knows what is expected and the Major receives focused information."),
    q("The Major learns from one Captain that two other Captains have a significant conflict affecting their coordination for weeks. Neither has reported it. The Major's first action is:",
      "Contact both Captains separately to verify the information before taking any action.",
      "Address the non-reporting first, then address the conflict.",
      "Convene a three-way conversation with both Captains to address the conflict directly.",
      "Ask the reporting Captain to facilitate reconciliation since she knows both parties.",
      "A",
      "Verify before acting. The Major received one account of a conflict she has not observed. She contacts both Captains separately — without revealing the source — and asks about the relationship. Acting on an unverified account risks compounding a problem she does not yet fully understand."),
    q("The most important information the Major needs from her Captains regularly is:",
      "Financial performance — budget adherence and resource utilization.",
      "Program metrics — event attendance, member participation, formation completions.",
      "The real condition of the community — what is actually happening, what is working, what is struggling, and what the Captain is worried about.",
      "Officer pipeline status — who is in formation, who is ready for advancement.",
      "C",
      "The Major most needs what formal reports rarely capture: the real condition of the community. What the Captain is worried about describes the present and the depth. Formal reporting is necessary; honest informal communication is irreplaceable."),
    q("The Major builds inter-Captain coordination best by:",
      "Requiring Captains to copy her on all inter-commandery communication.",
      "Creating structures and occasions for Captains to work directly with each other — regional projects, peer learning groups, joint events — and then stepping back to let those relationships develop.",
      "Sharing each Captain's contact information with the others and encouraging direct communication.",
      "Assigning each Captain a peer buddy for mutual support.",
      "B",
      "Inter-Captain coordination develops through shared work, not structure alone. The Major who creates regional projects requiring Captains to coordinate — and then steps back — builds the relationships and habits that make coordination natural."),
    q("Captains submit reports with wildly different timing and depth: some exactly at deadline, some early with minimal content, some late with detailed content. This variation primarily signals:",
      "Differences in individual work style.",
      "Unclear reporting expectations — Captains are making different trade-offs because they do not know what the Major actually values.",
      "Differences in commandery capacity.",
      "Both individual style and unclear expectations.",
      "B",
      "Systematic variation in reporting behavior usually signals unclear expectations. The Major who clarifies what she actually needs — not just timing but content, depth, and format — will produce more consistent and useful reports."),
    q("Creating order at the regional level means:",
      "Ensuring all commanderies follow the same procedures consistently.",
      "Building the conditions under which the region's work can proceed reliably — clear roles, predictable processes, honest information flow, and aligned expectations — so that energy can be directed at the mission rather than at managing uncertainty.",
      "Preventing and resolving conflicts between commanderies and officers.",
      "Maintaining compliance with the Order's governing documents.",
      "B",
      "Order is not uniformity — it is the stable condition under which work happens reliably. The Major who neglects order creates a region where Captains constantly manage uncertainty, compensating for unreliable systems. That energy is taken from the mission."),
    q("The Major's personal communication standard matters because:",
      "She should communicate frequently and accessibly so Captains feel supported.",
      "Her words carry authority, and imprecise or dishonest communication from the Major corrupts the entire regional communication culture.",
      "She should communicate through formal channels to establish appropriate professional distance.",
      "She should communicate proactively on significant issues and reactively on routine ones.",
      "B",
      "The Major's communication sets the tone for the entire region. If the Major is vague, Captains learn to manage vagueness. If she is precise and honest, the region learns that honest communication is valued and safe.")
  ]
))

# W10
MAJOR_WEEKS_DEF.append((
  "Week 10: Correction, Intervention, and Restoration at the Regional Level",
  "Handling disorder appropriately, intervening in failing local bodies, and guiding restoration.",
  _major_reading(),
  ["regional correction","intervention","restoration","failing commandery","justice"],
  [
    q("A commandery has been declining for 18 months — shrinking membership, disengaged Captain, cancelled programs. The Major has given feedback twice with no change. The appropriate next step is:",
      "Give more time — 18 months is insufficient to judge long-term trajectory.",
      "Move to formal intervention — name the pattern explicitly, establish a clear improvement timeline with specific benchmarks, and identify consequences if the trajectory does not reverse.",
      "Remove the Captain and appoint a new one.",
      "Consider whether the commandery should be merged with a stronger neighboring body.",
      "B",
      "Eighteen months of decline and two rounds of feedback without change requires a shift from advisory engagement to formal intervention. Continuing to advise without consequence signals the situation is not truly serious."),
    q("Before formally intervening in a struggling commandery, the most important thing the Major must verify is:",
      "That the Captain has been informed of the Major's concerns.",
      "That the decline is real and not a temporary fluctuation.",
      "That senior leadership has been briefed.",
      "That the Major has offered sufficient support and the current situation is genuinely not addressable through normal advisory channels.",
      "D",
      "The Major's intervention must be preceded by genuine support. Before intervening formally, she must be satisfied she has provided real support — not just observations — and that the situation genuinely exceeds what normal guidance can address."),
    q("Correction differs from discipline at the regional level in that:",
      "Correction addresses behavior; discipline addresses attitude.",
      "Correction is formational — aimed at changing understanding and behavior through honest feedback and support. Discipline is consequential — imposing penalties when correction has failed to produce change.",
      "Correction is the Major's tool; discipline is senior leadership's tool.",
      "There is no meaningful distinction — all correction involves some element of consequence.",
      "B",
      "Correction and discipline are sequentially related. The Major who reaches for discipline before exhausting correction is unjust. The Major who continues correcting without ever imposing consequences when correction fails is ineffective."),
    q("A Captain privately discloses that she believes her commandery is in crisis but does not know how to ask for help without appearing incompetent. The Major's response is:",
      "Reassure the Captain that admitting difficulty is a sign of strength, then ask her to describe the crisis in detail.",
      "Tell the Captain she should have raised this earlier and establish a corrective plan.",
      "Receive the disclosure with genuine care, ask the Captain to describe the situation fully, then determine together what kind of support is most needed.",
      "Thank the Captain for her honesty and commit to an unannounced inspection to verify.",
      "C",
      "A Captain who voluntarily discloses a crisis is showing exactly the kind of honesty that regional relationships are built on. The Major receives this with genuine care — not with correction for delayed disclosure. She asks, listens, and determines support collaboratively."),
    q("When weighing whether to remove a Captain who has repeatedly failed to meet standards, the Major must consider:",
      "Whether the Captain's failures have been documented.",
      "Whether the Captain was given genuinely adequate support and clear expectations.",
      "Whether the Captain's removal will destabilize the commandery more than her continued presence.",
      "All of the above.",
      "D",
      "Removal is the most significant personnel decision a Major makes, requiring honest engagement with all three considerations. A removal justified on accountability grounds but poorly timed or managed can damage the very community it is intended to help."),
    q("After removing a Captain, the Major must stabilize the affected commandery. Her most important first action is:",
      "Appoint an interim Captain immediately to re-establish clear leadership.",
      "Communicate with the commandery's members directly — name that a leadership change has occurred, acknowledge any disruption, and establish clear expectations for the transition period.",
      "Conduct a rapid assessment of the commandery's condition before making any personnel decisions.",
      "Convene the commandery's officers to govern collectively while a permanent Captain is identified.",
      "B",
      "Communication comes first. The Major who removes a Captain and is then silent creates a vacuum that rumors and anxiety will fill. She communicates directly and honestly with the community, re-establishing the sense that the situation is in hand."),
    q("Restoration differs from resolution in the context of regional correction in that:",
      "Resolution ends the conflict; restoration heals the relationship.",
      "Resolution addresses the presenting problem; restoration returns the community or officer to full health and function. Resolution can be achieved quickly; restoration takes time.",
      "Both A and B — they are sequentially related, with resolution enabling restoration.",
      "Restoration is the goal; resolution is the means.",
      "B",
      "Resolution and restoration are distinct temporal achievements. A conflict can be resolved without the community being restored to full health. Restoration means relationships have healed, trust has been rebuilt, and the community can function normally again."),
    q("A Major is called to intervene in a commandery where two officers are in open conflict that has divided the community. She should:",
      "Adjudicate the conflict — determine who is right and issue a binding decision.",
      "Remove both officers.",
      "Separate the parties for private conversations before any joint encounter, understand each person's perspective fully, then facilitate a structured reconciliation process.",
      "Ask the commandery's members to weigh in before making any decisions.",
      "C",
      "The Major's intervention begins privately. Joint confrontation before individual conversations almost always escalates. She meets with each officer privately, listens fully, and understands what is actually driving the conflict before facilitating the joint process."),
    q("The Major's responsibility to a Captain who has been corrected and is working to improve is:",
      "To monitor her progress and report honestly on whether improvement is occurring.",
      "To continue providing clear feedback while also providing genuine support — the Captain in an improvement process needs both accountability and encouragement.",
      "To step back and give the Captain space to implement the corrective plan.",
      "To protect the Captain's privacy.",
      "B",
      "The Major who corrects and then disappears has invested in accountability without investing in success. Accountability without support is punitive. Support without accountability is empty."),
    q("What does the pattern of interventions across a region reveal?",
      "Which commanderies are strongest and weakest, enabling resource allocation decisions.",
      "Whether the Major's standards are appropriately calibrated.",
      "The systemic conditions that support or undermine healthy commandery function — the Major who reads this pattern can identify regional investments that prevent future problems.",
      "How well Captains were selected and developed.",
      "C",
      "Intervention patterns are diagnostic information about the region. If the Major repeatedly intervenes in commanderies with new Captains, the transition support process may be inadequate. Reading the pattern as regional health data identifies systemic investments that prevent future interventions.")
  ]
))

# W11
MAJOR_WEEKS_DEF.append((
  "Week 11: Regional Oversight Practicum",
  "Applying regional oversight principles through a structured, real-world assessment and coordination exercise.",
  _major_reading(),
  ["regional practicum","oversight exercise","coordination assessment","leadership integration","real-world application"],
  [
    q("The Regional Oversight Practicum requires the Major to assess her entire region simultaneously. The most important preparation before conducting the assessment is:",
      "Gather all commandery reports and performance data from the past year.",
      "Notify all Captains that the assessment is coming.",
      "Clarify internally what healthy regional function looks like — define the criteria before gathering data, so the assessment produces an honest diagnosis rather than an impression.",
      "Identify which commanderies are likely to present concerns to allocate assessment time efficiently.",
      "C",
      "Assessment without defined criteria produces impressions, not diagnoses. The Major who defines what health looks like before gathering data produces an honest and useful assessment. Criteria first; data second."),
    q("During the regional assessment, the Major discovers the commanderies with the longest-tenured Captains show more stagnation than those with newer leadership. She should:",
      "Note it in her assessment report as a concern requiring future attention.",
      "Investigate the pattern before drawing conclusions — is tenure driving stagnation, or is there a confounding variable?",
      "Address the specific stagnating commanderies without drawing a general conclusion about tenure.",
      "Raise the pattern with senior leadership as a potential structural issue.",
      "B",
      "Unexpected patterns require investigation before action. Tenure and stagnation may be correlated for several reasons. The Major investigates before drawing conclusions — acting on a misunderstood pattern can produce harm."),
    q("The practicum requires the Major to present a regional health assessment to senior leadership. Her assessment reveals significant problems in two commanderies. She is tempted to soften the findings. The right posture is:",
      "Present the findings as written — the assessment's value depends on honesty.",
      "Present the findings with context — name the problems clearly but also describe the actions already underway to address them.",
      "Delay the presentation until problems are more advanced in resolution.",
      "Consult with affected Captains before the presentation to ensure they are aware.",
      "B",
      "Honest presentation with context is the right posture. The Major presents problems clearly — not softened — and also describes what she is already doing. This demonstrates both accountability and competence."),
    q("A Captain refuses to participate in a regional coordination exercise, claiming her commandery is too busy. The Major should:",
      "Excuse the Captain — local obligations are legitimate.",
      "Address the refusal directly: regional coordination exercises are not optional, and persistent non-participation is an accountability issue.",
      "Design the exercise so the Captain's participation is not required.",
      "Report the refusal to senior leadership as a compliance issue.",
      "B",
      "Regional exercises are not optional. The Captain who claims local busyness is misunderstanding the relationship between local obligations and regional responsibilities. If there is a genuine conflict, the solution is to negotiate timing — not to decline."),
    q("The practicum requires the Major to coordinate a region-wide activity. One commandery falls behind and threatens to delay the whole project. The Major should:",
      "Absorb the gap from regional resources to keep the project on schedule.",
      "Escalate to the affected Captain immediately — name the impact, ask what is driving the delay, and determine what support is needed to close the gap.",
      "Extend the project timeline to accommodate the delay.",
      "Proceed without the delayed commandery's contribution.",
      "B",
      "The Major names the impact and investigates the cause before deciding on a response. The delay may be a capacity problem, a priority problem, or an information problem. Acting before diagnosing risks solving the wrong problem."),
    q("What does the practicum reveal about the Major that a written assessment cannot?",
      "How she performs under the time pressure and complexity of real regional coordination.",
      "Whether her understanding of regional health is accurate.",
      "How she responds when things go wrong.",
      "All of the above.",
      "D",
      "The practicum tests formation that cannot be assessed on paper. Time pressure, unexpected complications, and the gap between anticipated and actual results reveal dimensions of regional command that can only be assessed through real exercise."),
    q("After the regional coordination exercise concludes, the Major conducts an after-action review and one Captain is defensive about her commandery's performance. The Major should:",
      "Redirect the Captain — the after-action review is not the place for defense.",
      "Give the defensive Captain space to explain before the group moves forward, since unaddressed defensiveness will contaminate the review.",
      "Privately message the Captain to ask her to lower her defensiveness.",
      "Proceed with the review without pressing the defensive Captain.",
      "B",
      "Defensiveness in a group review signals the Captain feels attacked. The Major who gives her space to explain may discover the performance concern identified is actually a symptom of something the Major missed."),
    q("The most important lesson the practicum is designed to produce is:",
      "Mastery of technical skills required for regional coordination.",
      "Confidence in the Major's ability to govern under real-world conditions.",
      "The integration of all prior formation — oversight, accountability, development, communication, correction — into a single coherent act of regional leadership, revealing both competence and remaining edges of growth.",
      "A documented case study for the board review.",
      "C",
      "The practicum's purpose is integration, not demonstration. The honest encounter with both competence and gap is the formation the practicum is designed to produce."),
    q("How does the Major use the practicum experience in preparing for her board review?",
      "She summarizes the practicum's outcomes in her portfolio as evidence of regional leadership capability.",
      "She uses the practicum's specific moments — decisions under pressure, gaps discovered, corrections executed — as the concrete material from which her board narrative is constructed.",
      "She prepares a formal case study of the practicum that reviewers can assess independently.",
      "She focuses board preparation on areas where the practicum revealed gaps.",
      "B",
      "The practicum is the Major's richest source of board material — because it is real. The specific honest stories it produced are the concrete material from which genuine formation narratives are built."),
    q("What does a Major learn from the practicum that the program's conceptual material alone cannot provide?",
      "The specific application of theoretical principles to her actual region.",
      "The gap between what she thought she knew and what she actually does when governing under real conditions — the practicum reveals the difference between understanding and embodiment.",
      "The specific strengths and weaknesses of her individual Captains under coordinated pressure.",
      "The structural limitations of her regional design.",
      "B",
      "The practicum's irreplaceable gift is the revelation of the gap between understanding and embodiment. The practicum makes visible what conceptual study cannot: who the Major actually is when governing under pressure.")
  ]
))

# W12
MAJOR_WEEKS_DEF.append((
  "Week 12: Capstone Preparation and Major's Board Review",
  "Compiling the final portfolio, finalizing reflections, and preparing for the oral board review.",
  _major_reading(),
  ["Major board review","capstone portfolio","final integration","oral review","readiness"],
  [
    q("The Major's capstone portfolio must demonstrate regional formation, not regional management. What distinguishes the two?",
      "Regional management documents outcomes; regional formation documents the process by which the Major developed her capacity to produce those outcomes.",
      "Regional management is an organizational achievement; regional formation is a personal one — the portfolio should focus on what happened to the Major, not what the Major made happen.",
      "There is no meaningful distinction at the Major level.",
      "Both A and B — the portfolio must show both what changed in the region and what changed in the Major herself.",
      "D",
      "The most compelling capstone portfolios track two parallel narratives: what happened in the region and what happened in the Major. The board is looking for both — regional outcomes as evidence the Major led, and personal change as evidence the Major was formed."),
    q("When asked 'What is the hardest thing you had to do in this program?' at the board review, the answer most valued by experienced reviewers describes:",
      "A technically complex task.",
      "A moment of genuine internal resistance — a place where the right action conflicted with the Major's comfort, preferences, or self-image, and she did it anyway.",
      "The scope of the Major's responsibilities.",
      "The practicum, which brought all prior formation to bear simultaneously.",
      "B",
      "Experienced reviewers are looking for character under pressure. The moment that cost something — where acting rightly required overcoming the Major's own reluctance — reveals character that no credentials can demonstrate."),
    q("The Major's portfolio reveals a major mistake she made early in the program that she later recognized and corrected. She should:",
      "Omit it — portfolios should emphasize growth and positive outcomes.",
      "Include it briefly — acknowledged errors show self-awareness without making the portfolio a confession.",
      "Include it fully — the mistake, what she learned, and how she corrected course are the most compelling formation narrative the portfolio can include.",
      "It depends on whether the mistake affected people negatively.",
      "C",
      "Mistakes with honest reflection are the core of formation portfolios. The combination of honesty and growth is rarer and more valuable than a clean record."),
    q("A board reviewer pushes back on a position the Major took in her portfolio — 'I disagree with your conclusion here.' The right response is:",
      "Defend her position — she thought it through carefully.",
      "Agree with the reviewer — disagreeing during the review creates conflict.",
      "Engage genuinely: 'Can you say more about what you see differently? I want to understand your concern.' Then respond honestly — updating her view if the reviewer's argument is stronger, or respectfully maintaining her position with reasons if it is not.",
      "Acknowledge the perspective without committing: 'I see why that's a concern — I'll continue to think about it.'",
      "C",
      "The board is looking for genuine intellectual engagement. Capitulation to social pressure and deflection to avoid conflict are both signals of a leader who manages appearances rather than pursues truth."),
    q("The Major's responsibility to the Captains and region she is leaving at the conclusion of her program is:",
      "To ensure all regional projects and initiatives are documented for her successor.",
      "To brief her successor thoroughly on every commandery.",
      "To leave the region measurably stronger than she received it — stronger Captains, healthier commanderies, clearer standards, a deeper pipeline.",
      "Both B and C.",
      "D",
      "The Major's departure responsibility is both relational (thorough briefing) and structural (leaving the region demonstrably stronger). Both are necessary acts of stewardship."),
    q("How does the Major's board review differ from the boards of lower ranks?",
      "The Major's board focuses more on strategic thinking and less on doctrinal knowledge.",
      "The Major's board assesses not just personal formation but regional formation — whether she developed a stronger region, not just a stronger self.",
      "The Major's board is conducted by more senior reviewers applying more rigorous standards.",
      "The Major's board is more comprehensive, covering all five pillars with greater depth.",
      "B",
      "The Major's board introduces a dimension absent from lower-rank reviews: regional accountability. The question is not only 'who have you become?' but 'what did you build and strengthen?'"),
    q("The most common way Major-level candidates fail their board review is:",
      "Insufficient knowledge of Order history and doctrine.",
      "Inability to demonstrate concrete regional outcomes — candidates can articulate principles but cannot point to specific changes they made in actual commanderies.",
      "Over-confidence.",
      "Weak communication skills.",
      "B",
      "The most common Major-level board failure is the abstraction gap. The board probes: 'Name a commandery that is stronger because of how you governed it. What exactly did you do? How do you know?' The candidate who cannot answer with specifics has studied regional leadership, not done it."),
    q("A Major candidate arrives at her board review aware that one aspect of her regional leadership was genuinely weak. She should:",
      "Raise the weakness proactively — name it honestly before reviewers identify it, and describe what she learned from it.",
      "Prepare thoroughly for every other topic so the board's limited time does not reach the weak area.",
      "Address it honestly only if asked.",
      "Reframe the weakness as an area of ongoing development.",
      "A",
      "Proactive disclosure of weakness is the most compelling signal of genuine formation. The board almost always already knows the weakness; the question is whether the candidate knows it too. Raising it first signals that she does."),
    q("The final test of a Major's formation is:",
      "Whether she can articulate a coherent philosophy of regional leadership.",
      "Whether the commanderies in her region are measurably healthier — stronger Captains, deeper formation, cleaner accountability — than when she received them.",
      "Whether she is ready for the Commander level.",
      "Whether the board unanimously endorses her advancement.",
      "B",
      "The Major's formation is ultimately tested by what the region became. The honest test: did the region become stronger under her watch? Did Captains develop? Did the mission advance? The Major who answers with specific, honest examples has passed the test that matters most."),
    q("What does the Major program ultimately aim to produce?",
      "Officers knowledgeable in provincial governance, regional administration, and Officer formation principles.",
      "Leaders changed by the weight of regional responsibility — tried by the complexity of governing multiple communities and developed in judgment, character, and relational capacity that only that kind of testing produces.",
      "Officers qualified to serve at the Commander level.",
      "Regional stewards who have strengthened the specific communities entrusted to them.",
      "B",
      "The Major program aims to produce leaders changed by weight. Leading through others, governing what you cannot directly see, holding a region's health in trust: these produce a different kind of leader than any prior rank.")
  ]
))

MAJOR_WEEKS = []
for i, d in enumerate(MAJOR_WEEKS_DEF):
    title, focus, reading, terms, questions = d
    MAJOR_WEEKS.append({
        "week_number": i+1, "week_title": title, "focus": focus,
        "passing_score": 70,
        "study_prompt": "Review all assigned documents before the quiz.",
        "required_reading": reading,
        "key_terms": terms,
        "quiz_questions": questions,
        "discussion_questions": [
            "How does this week's concept reshape your understanding of regional leadership responsibility?",
            "Where in your current context do you see this principle most urgently needed?",
            "What would embodying this standard require you to change in your current approach?"
        ],
    })
print("Major weeks built:", len(MAJOR_WEEKS))
